/**
 * Helper class for Languages
 * @name Language
 * @revision 7
 * @minimumVersion 1.0.0.0
 */
 export class Language
 {    

    findLanguage(language)
    {
        if(!language)
            return language;

        let ll = language.toLocaleLowerCase();

        let lang = this.Languages.filter(x => x.iso1 === ll 
            || x.iso2 === ll 
            || x.iso2b === ll 
            || x.iso3 === ll 
            || x.english?.toLocaleLowerCase() === ll 
            || x.french?.toLocaleLowerCase() === ll 
            || x.german?.toLocaleLowerCase() === ll
            || (x.aliases && x.aliases.test(ll))
        );
        if(!lang.length){
            Logger.WLog('Failed to locate language: ' + language);
            return null;
        }
        lang = lang[0];
        Logger.DLog('Found language for ' + language, lang);
        return lang;
    }
    /**
     * Gets the english name for a language
     * @param {string} language the language to lookup
     * @returns the english name, if not known will return the original name
     */
    getEnglishFor(language){        
        
        let lang = this.findLanguage(language);
        if(lang?.english?.length) return lang.english;             
        return language;
    }
    
    /**
     * Gets the ISO-639-1 code for a language
     * @param {string} language the language to lookup
     * @returns the ISO-639-1 code, if not known will return the original name
     */
    getIso1Code(language) {
        let lang = this.findLanguage(language);
        if(lang?.iso1?.length) return lang.iso1;        
        return language;
    }
    
    /**
     * Gets the ISO-639-2 code for a language
     * @param {string} language the language to lookup
     * @returns the ISO-639-2 code, if not known will return the original name
     */
    getIso2Code(language) {
        let lang = this.findLanguage(language);
        if(lang?.iso2?.length) return lang.iso2;     
        return language;
    }

    constructor()
    {
        this.Languages = [
            { "english":"Afar", "french":"afar", "german":"Danakil-Sprache", "iso2":"aar", "iso1":"aa", "iso2b":"aar", "iso3":"aar" },
            { "english":"Abkhazian", "french":"abkhaze", "german":"Abchasisch", "iso2":"abk", "iso1":"ab", "iso2b":"abk", "iso3":"abk" },
            { "english":"Achinese", "french":"aceh", "german":"Aceh-Sprache", "iso2":"ace" },
            { "english":"Acoli", "french":"acoli", "german":"Acholi-Sprache", "iso2":"ach" },
            { "english":"Adangme", "french":"adangme", "german":"Adangme-Sprache", "iso2":"ada" },
            { "english":"Adyghe", "french":"adyghé", "german":"Adygisch", "iso2":"ady" },
            { "english":"Afro-Asiatic languages", "french":"afro-asiatiques, langues", "german":"Hamitosemitische Sprachen (Andere)", "iso2":"afa" },
            { "english":"Afrihili", "french":"afrihili", "german":"Afrihili", "iso2":"afh" },
            { "english":"Afrikaans", "french":"afrikaans", "german":"Afrikaans", "iso2":"afr", "iso1":"af", "iso2b":"afr", "iso3":"afr" },
            { "english":"Ainu", "french":"aïnou", "german":"Ainu-Sprache", "iso2":"ain" },
            { "english":"Akan", "french":"akan", "german":"Akan-Sprache", "iso2":"aka", "iso1":"ak", "iso2b":"aka", "iso3":"aka" },
            { "english":"Akkadian", "french":"akkadien", "german":"Akkadisch", "iso2":"akk" },
            { "english":"Albanian", "french":"albanais", "german":"Albanisch", "iso2":"sqi", "iso1":"sq", "iso2b":"sqi", "iso3":"alb" },
            { "english":"Aleut", "french":"aléoute", "german":"Aleutisch", "iso2":"ale" },
            { "english":"Algonquian languages", "french":"algonquines, langues", "german":"Algonkin-Sprachen (Andere)", "iso2":"alg" },
            { "english":"Southern Altai", "french":"altai du Sud", "german":"Altaisch", "iso2":"alt" },
            { "english":"Amharic", "french":"amharique", "german":"Amharisch", "iso2":"amh", "iso1":"am", "iso2b":"amh", "iso3":"amh" },
            { "english":"English, Old (ca.450-1100)", "french":"anglo-saxon (ca.450-1100)", "german":"Altenglisch", "iso2":"ang" },
            { "english":"Angika", "french":"angika", "german":"Anga-Sprache", "iso2":"anp" },
            { "english":"Apache languages", "french":"apaches, langues", "german":"Apachen-Sprachen", "iso2":"apa" },
            { "english":"Arabic", "french":"arabe", "german":"Arabisch", "iso2":"ara", "iso1":"ar", "iso2b":"ara", "iso3":"ara" },
            { "english":"Official Aramaic (700-300 BCE)", "french":"araméen d'empire (700-300 BCE)", "german":"Aramäisch", "iso2":"arc" },
            { "english":"Aragonese", "french":"aragonais", "german":"Aragonesisch", "iso2":"arg", "iso1":"an", "iso2b":"arg", "iso3":"arg" },
            { "english":"Armenian", "french":"arménien", "german":"Armenisch", "iso2":"hye", "iso1":"hy", "iso2b":"hye", "iso3":"arm" },
            { "english":"Mapudungun", "french":"mapudungun", "german":"Arauka-Sprachen", "iso2":"arn" },
            { "english":"Arapaho", "french":"arapaho", "german":"Arapaho-Sprache", "iso2":"arp" },
            { "english":"Artificial languages", "french":"artificielles, langues", "german":"Kunstsprachen (Andere)", "iso2":"art" },
            { "english":"Arawak", "french":"arawak", "german":"Arawak-Sprachen", "iso2":"arw" },
            { "english":"Assamese", "french":"assamais", "german":"Assamesisch", "iso2":"asm", "iso1":"as", "iso2b":"asm", "iso3":"asm" },
            { "english":"Asturian", "french":"asturien", "german":"Asturisch", "iso2":"ast" },
            { "english":"Athapascan languages", "french":"athapascanes, langues", "german":"Athapaskische Sprachen (Andere)", "iso2":"ath" },
            { "english":"Australian languages", "french":"australiennes, langues", "german":"Australische Sprachen", "iso2":"aus" },
            { "english":"Avaric", "french":"avar", "german":"Awarisch", "iso2":"ava", "iso1":"av", "iso2b":"ava", "iso3":"ava" },
            { "english":"Avestan", "french":"avestique", "german":"Avestisch", "iso2":"ave", "iso1":"ae", "iso2b":"ave", "iso3":"ave" },
            { "english":"Awadhi", "french":"awadhi", "german":"Awadhi", "iso2":"awa" },
            { "english":"Aymara", "french":"aymara", "german":"Aymará-Sprache", "iso2":"aym", "iso1":"ay", "iso2b":"aym", "iso3":"aym" },
            { "english":"Azerbaijani", "french":"azéri", "german":"Aserbeidschanisch", "iso2":"aze", "iso1":"az", "iso2b":"aze", "iso3":"aze" },
            { "english":"Banda languages", "french":"banda, langues", "german":"Banda-Sprachen (Ubangi-Sprachen)", "iso2":"bad" },
            { "english":"Bamileke languages", "french":"bamiléké, langues", "german":"Bamileke-Sprachen", "iso2":"bai" },
            { "english":"Bashkir", "french":"bachkir", "german":"Baschkirisch", "iso2":"bak", "iso1":"ba", "iso2b":"bak", "iso3":"bak" },
            { "english":"Baluchi", "french":"baloutchi", "german":"Belutschisch", "iso2":"bal" },
            { "english":"Bambara", "french":"bambara", "german":"Bambara-Sprache", "iso2":"bam", "iso1":"bm", "iso2b":"bam", "iso3":"bam" },
            { "english":"Balinese", "french":"balinais", "german":"Balinesisch", "iso2":"ban" },
            { "english":"Basque", "french":"basque", "german":"Baskisch", "iso2":"eus", "iso1":"eu", "iso2b":"eus", "iso3":"baq" },
            { "english":"Basa", "french":"basa", "german":"Basaa-Sprache", "iso2":"bas" },
            { "english":"Baltic languages", "french":"baltes, langues", "german":"Baltische Sprachen (Andere)", "iso2":"bat" },
            { "english":"Beja", "french":"bedja", "german":"Bedauye", "iso2":"bej" },
            { "english":"Belarusian", "french":"biélorusse", "german":"Weißrussisch", "iso2":"bel", "iso1":"be", "iso2b":"bel", "iso3":"bel" },
            { "english":"Bemba", "french":"bemba", "german":"Bemba-Sprache", "iso2":"bem" },
            { "english":"Bengali", "french":"bengali", "german":"Bengali", "iso2":"ben", "iso1":"bn", "iso2b":"ben", "iso3":"ben" },
            { "english":"Berber languages", "french":"berbères, langues", "german":"Berbersprachen (Andere)", "iso2":"ber" },
            { "english":"Bhojpuri", "french":"bhojpuri", "german":"Bhojpuri", "iso2":"bho" },
            { "english":"Bihari languages", "french":"langues biharis", "german":"Bihari (Andere)", "iso2":"bih", "iso1":"bh" },
            { "english":"Bikol", "french":"bikol", "german":"Bikol-Sprache", "iso2":"bik" },
            { "english":"Bini", "french":"bini", "german":"Edo-Sprache", "iso2":"bin" },
            { "english":"Bislama", "french":"bichlamar", "german":"Beach-la-mar", "iso2":"bis", "iso1":"bi", "iso2b":"bis", "iso3":"bis" },
            { "english":"Siksika", "french":"blackfoot", "german":"Blackfoot-Sprache", "iso2":"bla" },
            { "english":"Bantu languages", "french":"bantou, langues", "german":"Bantusprachen (Andere)", "iso2":"bnt" },
            { "english":"Tibetan", "french":"tibétain", "german":"Tibetisch", "iso2":"bod", "iso1":"bo", "iso2b":"bod", "iso3":"tib" },
            { "english":"Bosnian", "french":"bosniaque", "german":"Bosnisch", "iso2":"bos", "iso1":"bs", "iso2b":"bos", "iso3":"bos" },
            { "english":"Braj", "french":"braj", "german":"Braj-Bhakha", "iso2":"bra" },
            { "english":"Breton", "french":"breton", "german":"Bretonisch", "iso2":"bre", "iso1":"br", "iso2b":"bre", "iso3":"bre" },
            { "english":"Batak languages", "french":"batak, langues", "german":"Batak-Sprache", "iso2":"btk" },
            { "english":"Buriat", "french":"bouriate", "german":"Burjatisch", "iso2":"bua" },
            { "english":"Buginese", "french":"bugi", "german":"Bugi-Sprache", "iso2":"bug" },
            { "english":"Bulgarian", "french":"bulgare", "german":"Bulgarisch", "iso2":"bul", "iso1":"bg", "iso2b":"bul", "iso3":"bul" },
            { "english":"Burmese", "french":"birman", "german":"Birmanisch", "iso2":"mya", "iso1":"my", "iso2b":"mya", "iso3":"bur" },
            { "english":"Blin", "french":"blin", "german":"Bilin-Sprache", "iso2":"byn" },
            { "english":"Caddo", "french":"caddo", "german":"Caddo-Sprachen", "iso2":"cad" },
            { "english":"Central American Indian languages", "french":"amérindiennes de l'Amérique centrale,  langues", "german":"Indianersprachen, Zentralamerika (Andere)", "iso2":"cai" },
            { "english":"Galibi Carib", "french":"karib", "german":"Karibische Sprachen", "iso2":"car" },
            { "english":"Catalan", "french":"catalan", "german":"Katalanisch", "iso2":"cat", "iso1":"ca" },
            { "english":"Caucasian languages", "french":"caucasiennes, langues", "german":"Kaukasische Sprachen (Andere)", "iso2":"cau" },
            { "english":"Cebuano", "french":"cebuano", "german":"Cebuano", "iso2":"ceb" },
            { "english":"Celtic languages", "french":"celtiques, langues", "german":"Keltische Sprachen (Andere)", "iso2":"cel" },
            { "english":"Czech", "french":"tchèque", "german":"Tschechisch", "iso2":"ces", "iso1":"cs", "iso2b":"ces", "iso3":"cze" },
            { "english":"Chamorro", "french":"chamorro", "german":"Chamorro-Sprache", "iso2":"cha", "iso1":"ch", "iso2b":"cha", "iso3":"cha" },
            { "english":"Chibcha", "french":"chibcha", "german":"Chibcha-Sprachen", "iso2":"chb" },
            { "english":"Chechen", "french":"tchétchène", "german":"Tschetschenisch", "iso2":"che", "iso1":"ce", "iso2b":"che", "iso3":"che" },
            { "english":"Chagatai", "french":"djaghataï", "german":"Tschagataisch", "iso2":"chg" },
            { "english":"Chinese", "french":"chinois", "german":"Chinesisch", "iso2":"zho", "iso1":"zh", "aliases":/^(chi|cn)$/i, "iso2b":"zho", "iso3":"chi" },
            { "english":"Chuukese", "french":"chuuk", "german":"Trukesisch", "iso2":"chk" },
            { "english":"Mari", "french":"mari", "german":"Tscheremissisch", "iso2":"chm" },
            { "english":"Chinook jargon", "french":"chinook, jargon", "german":"Chinook-Jargon", "iso2":"chn" },
            { "english":"Choctaw", "french":"choctaw", "german":"Choctaw-Sprache", "iso2":"cho" },
            { "english":"Chipewyan", "french":"chipewyan", "german":"Chipewyan-Sprache", "iso2":"chp" },
            { "english":"Cherokee", "french":"cherokee", "german":"Cherokee-Sprache", "iso2":"chr" },
            { "english":"Church Slavic", "french":"slavon d'église", "german":"Kirchenslawisch", "iso2":"chu", "iso1":"cu" },
            { "english":"Chuvash", "french":"tchouvache", "german":"Tschuwaschisch", "iso2":"chv", "iso1":"cv", "iso2b":"chv", "iso3":"chv" },
            { "english":"Cheyenne", "french":"cheyenne", "german":"Cheyenne-Sprache", "iso2":"chy" },
            { "english":"Chamic languages", "french":"chames, langues", "german":"Cham-Sprachen", "iso2":"cmc" },
            { "english":"Coptic", "french":"copte", "german":"Koptisch", "iso2":"cop" },
            { "english":"Cornish", "french":"cornique", "german":"Kornisch", "iso2":"cor", "iso1":"kw", "iso2b":"cor", "iso3":"cor" },
            { "english":"Corsican", "french":"corse", "german":"Korsisch", "iso2":"cos", "iso1":"co", "iso2b":"cos", "iso3":"cos" },
            { "english":"Creoles and pidgins, English based", "french":"créoles et pidgins basés sur l'anglais", "german":"Kreolisch-Englisch (Andere)", "iso2":"cpe" },
            { "english":"Creoles and pidgins, French-based", "french":"créoles et pidgins basés sur le français", "german":"Kreolisch-Französisch (Andere)", "iso2":"cpf" },
            { "english":"Creoles and pidgins, Portuguese-based", "french":"créoles et pidgins basés sur le portugais", "german":"Kreolisch-Portugiesisch (Andere)", "iso2":"cpp" },
            { "english":"Cree", "french":"cree", "german":"Cree-Sprache", "iso2":"cre", "iso1":"cr", "iso2b":"cre", "iso3":"cre" },
            { "english":"Crimean Tatar", "french":"tatar de Crimé", "german":"Krimtatarisch", "iso2":"crh" },
            { "english":"Creoles and pidgins", "french":"créoles et pidgins", "german":"Kreolische Sprachen", "iso2":"crp" },
            { "english":"Kashubian", "french":"kachoube", "german":"Kaschubisch", "iso2":"csb" },
            { "english":"Cushitic languages", "french":"couchitiques,  langues", "german":"Kuschitische Sprachen (Andere)", "iso2":"cus" },
            { "english":"Welsh", "french":"gallois", "german":"Kymrisch", "iso2":"cym", "iso1":"cy", "iso2b":"cym", "iso3":"wel" },
            { "english":"Czech", "french":"tchèque", "german":"Tschechisch", "iso2":"ces", "iso1":"cs" },
            { "english":"Dakota", "french":"dakota", "german":"Dakota-Sprache", "iso2":"dak" },
            { "english":"Danish", "french":"danois", "german":"Dänisch", "iso2":"dan", "iso1":"da", "iso2b":"dan", "iso3":"dan" },
            { "english":"Dargwa", "french":"dargwa", "german":"Darginisch", "iso2":"dar" },
            { "english":"Land Dayak languages", "french":"dayak, langues", "german":"Dajakisch", "iso2":"day" },
            { "english":"Delaware", "french":"delaware", "german":"Delaware-Sprache", "iso2":"del" },
            { "english":"Slave (Athapascan)", "french":"esclave (athapascan)", "german":"Slave-Sprache", "iso2":"den" },
            { "english":"Dogrib", "french":"dogrib", "german":"Dogrib-Sprache", "iso2":"dgr" },
            { "english":"Dinka", "french":"dinka", "german":"Dinka-Sprache", "iso2":"din" },
            { "english":"Divehi", "french":"maldivien", "german":"Maledivisch", "iso2":"div", "iso1":"dv" },
            { "english":"Dogri", "french":"dogri", "german":"Dogri", "iso2":"doi" },
            { "english":"Dravidian languages", "french":"dravidiennes,  langues", "german":"Drawidische Sprachen (Andere)", "iso2":"dra" },
            { "english":"Lower Sorbian", "french":"bas-sorabe", "german":"Niedersorbisch", "iso2":"dsb" },
            { "english":"Duala", "french":"douala", "german":"Duala-Sprachen", "iso2":"dua" },
            { "english":"Dutch, Middle (ca.1050-1350)", "french":"néerlandais moyen (ca. 1050-1350)", "german":"Mittelniederländisch", "iso2":"dum" },
            { "english":"Dutch", "french":"néerlandais", "german":"Niederländisch", "iso2":"nld", "iso1":"nl" },
            { "english":"Dyula", "french":"dioula", "german":"Dyula-Sprache", "iso2":"dyu" },
            { "english":"Dzongkha", "french":"dzongkha", "german":"Dzongkha", "iso2":"dzo", "iso1":"dz", "iso2b":"dzo", "iso3":"dzo" },
            { "english":"Efik", "french":"efik", "german":"Efik", "iso2":"efi" },
            { "english":"Egyptian (Ancient)", "french":"égyptien", "german":"Ägyptisch", "iso2":"egy" },
            { "english":"Ekajuk", "french":"ekajuk", "german":"Ekajuk", "iso2":"eka" },
            { "english":"Greek, Modern (1453-)", "french":"grec moderne (après 1453)", "german":"Neugriechisch", "iso2":"ell", "iso1":"el" },
            { "english":"Elamite", "french":"élamite", "german":"Elamisch", "iso2":"elx" },
            { "english":"English", "french":"anglais", "german":"Englisch", "iso2":"eng", "iso1":"en", "iso2b":"eng", "iso3":"eng" },
            { "english":"English, Middle (1100-1500)", "french":"anglais moyen (1100-1500)", "german":"Mittelenglisch", "iso2":"enm" },
            { "english":"Esperanto", "french":"espéranto", "german":"Esperanto", "iso2":"epo", "iso1":"eo", "iso2b":"epo", "iso3":"epo" },
            { "english":"Estonian", "french":"estonien", "german":"Estnisch", "iso2":"est", "iso1":"et", "iso2b":"est", "iso3":"est" },
            { "english":"Basque", "french":"basque", "german":"Baskisch", "iso2":"eus", "iso1":"eu" },
            { "english":"Ewe", "french":"éwé", "german":"Ewe-Sprache", "iso2":"ewe", "iso1":"ee", "iso2b":"ewe", "iso3":"ewe" },
            { "english":"Ewondo", "french":"éwondo", "german":"Ewondo", "iso2":"ewo" },
            { "english":"Fang", "french":"fang", "german":"Pangwe-Sprache", "iso2":"fan" },
            { "english":"Faroese", "french":"féroïen", "german":"Färöisch", "iso2":"fao", "iso1":"fo", "iso2b":"fao", "iso3":"fao" },
            { "english":"Persian", "french":"persan", "german":"Persisch", "iso2":"fas", "iso1":"fa", "iso2b":"fas", "iso3":"per" },
            { "english":"Fanti", "french":"fanti", "german":"Fante-Sprache", "iso2":"fat" },
            { "english":"Fijian", "french":"fidjien", "german":"Fidschi-Sprache", "iso2":"fij", "iso1":"fj", "iso2b":"fij", "iso3":"fij" },
            { "english":"Filipino", "french":"filipino", "german":"Pilipino", "iso2":"fil" },
            { "english":"Finnish", "french":"finnois", "german":"Finnisch", "iso2":"fin", "iso1":"fi", "iso2b":"fin", "iso3":"fin" },
            { "english":"Finno-Ugrian languages", "french":"finno-ougriennes,  langues", "german":"Finnougrische Sprachen (Andere)", "iso2":"fiu" },
            { "english":"Fon", "french":"fon", "german":"Fon-Sprache", "iso2":"fon" },
            { "english":"French", "french":"français", "german":"Französisch", "iso2":"fra", "iso1":"fr", "iso2b":"fra", "iso3":"fre" },
            { "english":"French", "french":"français", "german":"Französisch", "iso2":"fra", "iso1":"fr" },
            { "english":"French, Middle (ca.1400-1600)", "french":"français moyen (1400-1600)", "german":"Mittelfranzösisch", "iso2":"frm" },
            { "english":"French, Old (842-ca.1400)", "french":"français ancien (842-ca.1400)", "german":"Altfranzösisch", "iso2":"fro" },
            { "english":"Northern Frisian", "french":"frison septentrional", "german":"Nordfriesisch", "iso2":"frr" },
            { "english":"Eastern Frisian", "french":"frison oriental", "german":"Ostfriesisch", "iso2":"frs" },
            { "english":"Western Frisian", "french":"frison occidental", "german":"Friesisch", "iso2":"fry", "iso1":"fy", "iso2b":"fry", "iso3":"fry" },
            { "english":"Fulah", "french":"peul", "german":"Ful", "iso2":"ful", "iso1":"ff", "iso2b":"ful", "iso3":"ful" },
            { "english":"Friulian", "french":"frioulan", "german":"Friulisch", "iso2":"fur" },
            { "english":"Gayo", "french":"gayo", "german":"Gayo-Sprache", "iso2":"gay" },
            { "english":"Gbaya", "french":"gbaya", "german":"Gbaya-Sprache", "iso2":"gba" },
            { "english":"Germanic languages", "french":"germaniques, langues", "german":"Germanische Sprachen (Andere)", "iso2":"gem" },
            { "english":"Georgian", "french":"géorgien", "german":"Georgisch", "iso2":"kat", "iso1":"ka", "iso2b":"kat", "iso3":"geo" },
            { "english":"German", "french":"allemand", "german":"Deutsch", "iso2":"deu", "iso1":"de", "aliases":/^ger$/i, "iso2b":"deu", "iso3":"ger" },
            { "english":"Geez", "french":"guèze", "german":"Altäthiopisch", "iso2":"gez" },
            { "english":"Gilbertese", "french":"kiribati", "german":"Gilbertesisch", "iso2":"gil" },
            { "english":"Gaelic", "french":"gaélique", "german":"Gälisch-Schottisch", "iso2":"gla", "iso1":"gd" },
            { "english":"Irish", "french":"irlandais", "german":"Irisch", "iso2":"gle", "iso1":"ga", "iso2b":"gle", "iso3":"gle" },
            { "english":"Galician", "french":"galicien", "german":"Galicisch", "iso2":"glg", "iso1":"gl", "iso2b":"glg", "iso3":"glg" },
            { "english":"Manx", "french":"manx", "german":"Manx", "iso2":"glv", "iso1":"gv", "iso2b":"glv", "iso3":"glv" },
            { "english":"German, Middle High (ca.1050-1500)", "french":"allemand, moyen haut (ca. 1050-1500)", "german":"Mittelhochdeutsch", "iso2":"gmh" },
            { "english":"German, Old High (ca.750-1050)", "french":"allemand, vieux haut (ca. 750-1050)", "german":"Althochdeutsch", "iso2":"goh" },
            { "english":"Gondi", "french":"gond", "german":"Gondi-Sprache", "iso2":"gon" },
            { "english":"Gorontalo", "french":"gorontalo", "german":"Gorontalesisch", "iso2":"gor" },
            { "english":"Gothic", "french":"gothique", "german":"Gotisch", "iso2":"got" },
            { "english":"Grebo", "french":"grebo", "german":"Grebo-Sprache", "iso2":"grb" },
            { "english":"Greek, Ancient (to 1453)", "french":"grec ancien (jusqu'à 1453)", "german":"Griechisch", "iso2":"grc" },
            { "english":"Greek, Modern (1453-)", "french":"grec moderne (après 1453)", "german":"Neugriechisch", "iso2":"ell", "iso1":"el" },
            { "english":"Guarani", "french":"guarani", "german":"Guaraní-Sprache", "iso2":"grn", "iso1":"gn", "iso2b":"grn", "iso3":"grn" },
            { "english":"Swiss German", "french":"suisse alémanique", "german":"Schweizerdeutsch", "iso2":"gsw" },
            { "english":"Gujarati", "french":"goudjrati", "german":"Gujarati-Sprache", "iso2":"guj", "iso1":"gu", "iso2b":"guj", "iso3":"guj" },
            { "english":"Gwich'in", "french":"gwich'in", "german":"Kutchin-Sprache", "iso2":"gwi" },
            { "english":"Haida", "french":"haida", "german":"Haida-Sprache", "iso2":"hai" },
            { "english":"Haitian", "french":"haïtien", "german":"Haïtien (Haiti-Kreolisch)", "iso2":"hat", "iso1":"ht" },
            { "english":"Hausa", "french":"haoussa", "german":"Haussa-Sprache", "iso2":"hau", "iso1":"ha", "iso2b":"hau", "iso3":"hau" },
            { "english":"Hawaiian", "french":"hawaïen", "german":"Hawaiisch", "iso2":"haw" },
            { "english":"Hebrew", "french":"hébreu", "german":"Hebräisch", "iso2":"heb", "iso1":"he", "iso2b":"heb", "iso3":"heb" },
            { "english":"Herero", "french":"herero", "german":"Herero-Sprache", "iso2":"her", "iso1":"hz", "iso2b":"her", "iso3":"her" },
            { "english":"Hiligaynon", "french":"hiligaynon", "german":"Hiligaynon-Sprache", "iso2":"hil" },
            { "english":"Himachali languages", "french":"langues himachalis", "german":"Himachali", "iso2":"him" },
            { "english":"Hindi", "french":"hindi", "german":"Hindi", "iso2":"hin", "iso1":"hi", "iso2b":"hin", "iso3":"hin" },
            { "english":"Hittite", "french":"hittite", "german":"Hethitisch", "iso2":"hit" },
            { "english":"Hmong", "french":"hmong", "german":"Miao-Sprachen", "iso2":"hmn" },
            { "english":"Hiri Motu", "french":"hiri motu", "german":"Hiri-Motu", "iso2":"hmo", "iso1":"ho", "iso2b":"hmo", "iso3":"hmo" },
            { "english":"Croatian", "french":"croate", "german":"Kroatisch", "iso2":"hrv", "iso1":"hr", "iso2b":"hrv", "iso3":"hrv" },
            { "english":"Upper Sorbian", "french":"haut-sorabe", "german":"Obersorbisch", "iso2":"hsb" },
            { "english":"Hungarian", "french":"hongrois", "german":"Ungarisch", "iso2":"hun", "iso1":"hu", "iso2b":"hun", "iso3":"hun" },
            { "english":"Hupa", "french":"hupa", "german":"Hupa-Sprache", "iso2":"hup" },
            { "english":"Armenian", "french":"arménien", "german":"Armenisch", "iso2":"hye", "iso1":"hy" },
            { "english":"Iban", "french":"iban", "german":"Iban-Sprache", "iso2":"iba" },
            { "english":"Igbo", "french":"igbo", "german":"Ibo-Sprache", "iso2":"ibo", "iso1":"ig", "iso2b":"ibo", "iso3":"ibo" },
            { "english":"Icelandic", "french":"islandais", "german":"Isländisch", "iso2":"isl", "iso1":"is", "iso2b":"isl", "iso3":"ice" },
            { "english":"Ido", "french":"ido", "german":"Ido", "iso2":"ido", "iso1":"io", "iso2b":"ido", "iso3":"ido" },
            { "english":"Sichuan Yi", "french":"yi de Sichuan", "german":"Lalo-Sprache", "iso2":"iii", "iso1":"ii" },
            { "english":"Ijo languages", "french":"ijo, langues", "german":"Ijo-Sprache", "iso2":"ijo" },
            { "english":"Inuktitut", "french":"inuktitut", "german":"Inuktitut", "iso2":"iku", "iso1":"iu", "iso2b":"iku", "iso3":"iku" },
            { "english":"Interlingue", "french":"interlingue", "german":"Interlingue", "iso2":"ile", "iso1":"ie" },
            { "english":"Iloko", "french":"ilocano", "german":"Ilokano-Sprache", "iso2":"ilo" },
            { "english":"Interlingua (International Auxiliary Language Association)", "french":"interlingua (langue auxiliaire internationale)", "german":"Interlingua", "iso2":"ina", "iso1":"ia", "iso2b":"ina", "iso3":"ina" },
            { "english":"Indic languages", "french":"indo-aryennes, langues", "german":"Indoarische Sprachen (Andere)", "iso2":"inc" },
            { "english":"Indonesian", "french":"indonésien", "german":"Bahasa Indonesia", "iso2":"ind", "iso1":"id", "iso2b":"ind", "iso3":"ind" },
            { "english":"Indo-European languages", "french":"indo-européennes, langues", "german":"Indogermanische Sprachen (Andere)", "iso2":"ine" },
            { "english":"Ingush", "french":"ingouche", "german":"Inguschisch", "iso2":"inh" },
            { "english":"Inupiaq", "french":"inupiaq", "german":"Inupik", "iso2":"ipk", "iso1":"ik", "iso2b":"ipk", "iso3":"ipk" },
            { "english":"Iranian languages", "french":"iraniennes, langues", "german":"Iranische Sprachen (Andere)", "iso2":"ira" },
            { "english":"Iroquoian languages", "french":"iroquoises, langues", "german":"Irokesische Sprachen", "iso2":"iro" },
            { "english":"Icelandic", "french":"islandais", "german":"Isländisch", "iso2":"isl", "iso1":"is" },
            { "english":"Italian", "french":"italien", "german":"Italienisch", "iso2":"ita", "iso1":"it", "iso2b":"ita", "iso3":"ita" },
            { "english":"Javanese", "french":"javanais", "german":"Javanisch", "iso2":"jav", "iso1":"jv", "iso2b":"jav", "iso3":"jav" },
            { "english":"Lojban", "french":"lojban", "german":"Lojban", "iso2":"jbo" },
            { "english":"Japanese", "french":"japonais", "german":"Japanisch", "iso2":"jpn", "iso1":"ja", "iso2b":"jpn", "iso3":"jpn" },
            { "english":"Judeo-Persian", "french":"judéo-persan", "german":"Jüdisch-Persisch", "iso2":"jpr" },
            { "english":"Judeo-Arabic", "french":"judéo-arabe", "german":"Jüdisch-Arabisch", "iso2":"jrb" },
            { "english":"Kara-Kalpak", "french":"karakalpak", "german":"Karakalpakisch", "iso2":"kaa" },
            { "english":"Kabyle", "french":"kabyle", "german":"Kabylisch", "iso2":"kab" },
            { "english":"Kachin", "french":"kachin", "german":"Kachin-Sprache", "iso2":"kac" },
            { "english":"Kalaallisut", "french":"groenlandais", "german":"Grönländisch", "iso2":"kal", "iso1":"kl" },
            { "english":"Kamba", "french":"kamba", "german":"Kamba-Sprache", "iso2":"kam" },
            { "english":"Kannada", "french":"kannada", "german":"Kannada", "iso2":"kan", "iso1":"kn", "iso2b":"kan", "iso3":"kan" },
            { "english":"Karen languages", "french":"karen, langues", "german":"Karenisch", "iso2":"kar" },
            { "english":"Kashmiri", "french":"kashmiri", "german":"Kaschmiri", "iso2":"kas", "iso1":"ks", "iso2b":"kas", "iso3":"kas" },
            { "english":"Georgian", "french":"géorgien", "german":"Georgisch", "iso2":"kat", "iso1":"ka" },
            { "english":"Kanuri", "french":"kanouri", "german":"Kanuri-Sprache", "iso2":"kau", "iso1":"kr", "iso2b":"kau", "iso3":"kau" },
            { "english":"Kawi", "french":"kawi", "german":"Kawi", "iso2":"kaw" },
            { "english":"Kazakh", "french":"kazakh", "german":"Kasachisch", "iso2":"kaz", "iso1":"kk", "iso2b":"kaz", "iso3":"kaz" },
            { "english":"Kabardian", "french":"kabardien", "german":"Kabardinisch", "iso2":"kbd" },
            { "english":"Khasi", "french":"khasi", "german":"Khasi-Sprache", "iso2":"kha" },
            { "english":"Khoisan languages", "french":"khoïsan, langues", "german":"Khoisan-Sprachen (Andere)", "iso2":"khi" },
            { "english":"Central Khmer", "french":"khmer central", "german":"Kambodschanisch", "iso2":"khm", "iso1":"km", "iso2b":"khm", "iso3":"khm" },
            { "english":"Khotanese", "french":"khotanais", "german":"Sakisch", "iso2":"kho" },
            { "english":"Kikuyu", "french":"kikuyu", "german":"Kikuyu-Sprache", "iso2":"kik", "iso1":"ki" },
            { "english":"Kinyarwanda", "french":"rwanda", "german":"Rwanda-Sprache", "iso2":"kin", "iso1":"rw", "iso2b":"kin", "iso3":"kin" },
            { "english":"Kirghiz", "french":"kirghiz", "german":"Kirgisisch", "iso2":"kir", "iso1":"ky" },
            { "english":"Kimbundu", "french":"kimbundu", "german":"Kimbundu-Sprache", "iso2":"kmb" },
            { "english":"Konkani", "french":"konkani", "german":"Konkani", "iso2":"kok" },
            { "english":"Komi", "french":"kom", "german":"Komi-Sprache", "iso2":"kom", "iso1":"kv", "iso2b":"kom", "iso3":"kom" },
            { "english":"Kongo", "french":"kongo", "german":"Kongo-Sprache", "iso2":"kon", "iso1":"kg", "iso2b":"kon", "iso3":"kon" },
            { "english":"Korean", "french":"coréen", "german":"Koreanisch", "iso2":"kor", "iso1":"ko", "iso2b":"kor", "iso3":"kor" },
            { "english":"Kosraean", "french":"kosrae", "german":"Kosraeanisch", "iso2":"kos" },
            { "english":"Kpelle", "french":"kpellé", "german":"Kpelle-Sprache", "iso2":"kpe" },
            { "english":"Karachay-Balkar", "french":"karatchai balkar", "german":"Karatschaiisch-Balkarisch", "iso2":"krc" },
            { "english":"Karelian", "french":"carélien", "german":"Karelisch", "iso2":"krl" },
            { "english":"Kru languages", "french":"krou, langues", "german":"Kru-Sprachen (Andere)", "iso2":"kro" },
            { "english":"Kurukh", "french":"kurukh", "german":"Oraon-Sprache", "iso2":"kru" },
            { "english":"Kuanyama", "french":"kuanyama", "german":"Kwanyama-Sprache", "iso2":"kua", "iso1":"kj" },
            { "english":"Kumyk", "french":"koumyk", "german":"Kumükisch", "iso2":"kum" },
            { "english":"Kurdish", "french":"kurde", "german":"Kurdisch", "iso2":"kur", "iso1":"ku", "iso2b":"kur", "iso3":"kur" },
            { "english":"Kutenai", "french":"kutenai", "german":"Kutenai-Sprache", "iso2":"kut" },
            { "english":"Ladino", "french":"judéo-espagnol", "german":"Judenspanisch", "iso2":"lad" },
            { "english":"Lahnda", "french":"lahnda", "german":"Lahnda", "iso2":"lah" },
            { "english":"Lamba", "french":"lamba", "german":"Lamba-Sprache (Bantusprache)", "iso2":"lam" },
            { "english":"Lao", "french":"lao", "german":"Laotisch", "iso2":"lao", "iso1":"lo", "iso2b":"lao", "iso3":"lao" },
            { "english":"Latin", "french":"latin", "german":"Latein", "iso2":"lat", "iso1":"la", "iso2b":"lat", "iso3":"lat" },
            { "english":"Latvian", "french":"letton", "german":"Lettisch", "iso2":"lav", "iso1":"lv", "iso2b":"lav", "iso3":"lav" },
            { "english":"Lezghian", "french":"lezghien", "german":"Lesgisch", "iso2":"lez" },
            { "english":"Limburgan", "french":"limbourgeois", "german":"Limburgisch", "iso2":"lim", "iso1":"li" },
            { "english":"Lingala", "french":"lingala", "german":"Lingala", "iso2":"lin", "iso1":"ln", "iso2b":"lin", "iso3":"lin" },
            { "english":"Lithuanian", "french":"lituanien", "german":"Litauisch", "iso2":"lit", "iso1":"lt", "iso2b":"lit", "iso3":"lit" },
            { "english":"Mongo", "french":"mongo", "german":"Mongo-Sprache", "iso2":"lol" },
            { "english":"Lozi", "french":"lozi", "german":"Rotse-Sprache", "iso2":"loz" },
            { "english":"Luxembourgish", "french":"luxembourgeois", "german":"Luxemburgisch", "iso2":"ltz", "iso1":"lb" },
            { "english":"Luba-Lulua", "french":"luba-lulua", "german":"Lulua-Sprache", "iso2":"lua" },
            { "english":"Luba-Katanga", "french":"luba-katanga", "german":"Luba-Katanga-Sprache", "iso2":"lub", "iso1":"lu", "iso2b":"lub", "iso3":"lub" },
            { "english":"Ganda", "french":"ganda", "german":"Ganda-Sprache", "iso2":"lug", "iso1":"lg", "iso2b":"lug", "iso3":"lug" },
            { "english":"Luiseno", "french":"luiseno", "german":"Luiseño-Sprache", "iso2":"lui" },
            { "english":"Lunda", "french":"lunda", "german":"Lunda-Sprache", "iso2":"lun" },
            { "english":"Luo (Kenya and Tanzania)", "french":"luo (Kenya et Tanzanie)", "german":"Luo-Sprache", "iso2":"luo" },
            { "english":"Lushai", "french":"lushai", "german":"Lushai-Sprache", "iso2":"lus" },
            { "english":"Macedonian", "french":"macédonien", "german":"Makedonisch", "iso2":"mkd", "iso1":"mk", "iso2b":"mkd", "iso3":"mac" },
            { "english":"Madurese", "french":"madourais", "german":"Maduresisch", "iso2":"mad" },
            { "english":"Magahi", "french":"magahi", "german":"Khotta", "iso2":"mag" },
            { "english":"Marshallese", "french":"marshall", "german":"Marschallesisch", "iso2":"mah", "iso1":"mh", "iso2b":"mah", "iso3":"mah" },
            { "english":"Maithili", "french":"maithili", "german":"Maithili", "iso2":"mai" },
            { "english":"Makasar", "french":"makassar", "german":"Makassarisch", "iso2":"mak" },
            { "english":"Malayalam", "french":"malayalam", "german":"Malayalam", "iso2":"mal", "iso1":"ml", "iso2b":"mal", "iso3":"mal" },
            { "english":"Mandingo", "french":"mandingue", "german":"Malinke-Sprache", "iso2":"man" },
            { "english":"Maori", "french":"maori", "german":"Maori-Sprache", "iso2":"mri", "iso1":"mi", "iso2b":"mri", "iso3":"mao" },
            { "english":"Austronesian languages", "french":"austronésiennes, langues", "german":"Austronesische Sprachen (Andere)", "iso2":"map" },
            { "english":"Marathi", "french":"marathe", "german":"Marathi", "iso2":"mar", "iso1":"mr", "iso2b":"mar", "iso3":"mar" },
            { "english":"Masai", "french":"massaï", "german":"Massai-Sprache", "iso2":"mas" },
            { "english":"Malay", "french":"malais", "german":"Malaiisch", "iso2":"msa", "iso1":"ms", "iso2b":"msa", "iso3":"may" },
            { "english":"Moksha", "french":"moksa", "german":"Mokscha-Sprache", "iso2":"mdf" },
            { "english":"Mandar", "french":"mandar", "german":"Mandaresisch", "iso2":"mdr" },
            { "english":"Mende", "french":"mendé", "german":"Mende-Sprache", "iso2":"men" },
            { "english":"Irish, Middle (900-1200)", "french":"irlandais moyen (900-1200)", "german":"Mittelirisch", "iso2":"mga" },
            { "english":"Mi'kmaq", "french":"mi'kmaq", "german":"Micmac-Sprache", "iso2":"mic" },
            { "english":"Minangkabau", "french":"minangkabau", "german":"Minangkabau-Sprache", "iso2":"min" },
            { "english":"Uncoded languages", "french":"langues non codées", "german":"Einzelne andere Sprachen", "iso2":"mis" },
            { "english":"Macedonian", "french":"macédonien", "german":"Makedonisch", "iso2":"mkd", "iso1":"mk" },
            { "english":"Mon-Khmer languages", "french":"môn-khmer, langues", "german":"Mon-Khmer-Sprachen (Andere)", "iso2":"mkh" },
            { "english":"Malagasy", "french":"malgache", "german":"Malagassi-Sprache", "iso2":"mlg", "iso1":"mg", "iso2b":"mlg", "iso3":"mlg" },
            { "english":"Maltese", "french":"maltais", "german":"Maltesisch", "iso2":"mlt", "iso1":"mt", "iso2b":"mlt", "iso3":"mlt" },
            { "english":"Manchu", "french":"mandchou", "german":"Mandschurisch", "iso2":"mnc" },
            { "english":"Manipuri", "french":"manipuri", "german":"Meithei-Sprache", "iso2":"mni" },
            { "english":"Manobo languages", "french":"manobo, langues", "german":"Manobo-Sprachen", "iso2":"mno" },
            { "english":"Mohawk", "french":"mohawk", "german":"Mohawk-Sprache", "iso2":"moh" },
            { "english":"Mongolian", "french":"mongol", "german":"Mongolisch", "iso2":"mon", "iso1":"mn", "iso2b":"mon", "iso3":"mon" },
            { "english":"Mossi", "french":"moré", "german":"Mossi-Sprache", "iso2":"mos" },
            { "english":"Maori", "french":"maori", "german":"Maori-Sprache", "iso2":"mri", "iso1":"mi" },
            { "english":"Malay", "french":"malais", "german":"Malaiisch", "iso2":"msa", "iso1":"ms" },
            { "english":"Multiple languages", "french":"multilingue", "german":"Mehrere Sprachen", "iso2":"mul" },
            { "english":"Munda languages", "french":"mounda, langues", "german":"Mundasprachen (Andere)", "iso2":"mun" },
            { "english":"Creek", "french":"muskogee", "german":"Muskogisch", "iso2":"mus" },
            { "english":"Mirandese", "french":"mirandais", "german":"Mirandesisch", "iso2":"mwl" },
            { "english":"Marwari", "french":"marvari", "german":"Marwari", "iso2":"mwr" },
            { "english":"Burmese", "french":"birman", "german":"Birmanisch", "iso2":"mya", "iso1":"my" },
            { "english":"Mayan languages", "french":"maya, langues", "german":"Maya-Sprachen", "iso2":"myn" },
            { "english":"Erzya", "french":"erza", "german":"Erza-Mordwinisch", "iso2":"myv" },
            { "english":"Nahuatl languages", "french":"nahuatl, langues", "german":"Nahuatl", "iso2":"nah" },
            { "english":"North American Indian languages", "french":"nord-amérindiennes, langues", "german":"Indianersprachen, Nordamerika (Andere)", "iso2":"nai" },
            { "english":"Neapolitan", "french":"napolitain", "german":"Neapel / Mundart", "iso2":"nap" },
            { "english":"Nauru", "french":"nauruan", "german":"Nauruanisch", "iso2":"nau", "iso1":"na", "iso2b":"nau", "iso3":"nau" },
            { "english":"Navajo", "french":"navaho", "german":"Navajo-Sprache", "iso2":"nav", "iso1":"nv" },
            { "english":"Ndebele, South", "french":"ndébélé du Sud", "german":"Ndebele-Sprache (Transvaal)", "iso2":"nbl", "iso1":"nr" },
            { "english":"Ndebele, North", "french":"ndébélé du Nord", "german":"Ndebele-Sprache (Simbabwe)", "iso2":"nde", "iso1":"nd" },
            { "english":"Ndonga", "french":"ndonga", "german":"Ndonga", "iso2":"ndo", "iso1":"ng", "iso2b":"ndo", "iso3":"ndo" },
            { "english":"Low German", "french":"bas allemand", "german":"Niederdeutsch", "iso2":"nds" },
            { "english":"Nepali", "french":"népalais", "german":"Nepali", "iso2":"nep", "iso1":"ne", "iso2b":"nep", "iso3":"nep" },
            { "english":"Nepal Bhasa", "french":"nepal bhasa", "german":"Newari", "iso2":"new" },
            { "english":"Nias", "french":"nias", "german":"Nias-Sprache", "iso2":"nia" },
            { "english":"Niger-Kordofanian languages", "french":"nigéro-kordofaniennes, langues", "german":"Nigerkordofanische Sprachen (Andere)", "iso2":"nic" },
            { "english":"Niuean", "french":"niué", "german":"Niue-Sprache", "iso2":"niu" },
            { "english":"Dutch", "french":"néerlandais", "german":"Niederländisch", "iso2":"nld", "iso1":"nl" },
            { "english":"Norwegian Nynorsk", "french":"norvégien nynorsk", "german":"Nynorsk", "iso2":"nno", "iso1":"nn", "iso2b":"nno", "iso3":"nno" },
            { "english":"Bokmål, Norwegian", "french":"norvégien bokmål", "german":"Bokmål", "iso2":"nob", "iso1":"nb" },
            { "english":"Nogai", "french":"nogaï", "german":"Nogaisch", "iso2":"nog" },
            { "english":"Norse, Old", "french":"norrois, vieux", "german":"Altnorwegisch", "iso2":"non" },
            { "english":"Norwegian", "french":"norvégien", "german":"Norwegisch", "iso2":"nor", "iso1":"no", "iso2b":"nor", "iso3":"nor" },
            { "english":"N'Ko", "french":"n'ko", "german":"N'Ko", "iso2":"nqo" },
            { "english":"Pedi", "french":"pedi", "german":"Pedi-Sprache", "iso2":"nso" },
            { "english":"Nubian languages", "french":"nubiennes, langues", "german":"Nubische Sprachen", "iso2":"nub" },
            { "english":"Classical Newari", "french":"newari classique", "german":"Alt-Newari", "iso2":"nwc" },
            { "english":"Chichewa", "french":"chichewa", "german":"Nyanja-Sprache", "iso2":"nya", "iso1":"ny" },
            { "english":"Nyamwezi", "french":"nyamwezi", "german":"Nyamwezi-Sprache", "iso2":"nym" },
            { "english":"Nyankole", "french":"nyankolé", "german":"Nkole-Sprache", "iso2":"nyn" },
            { "english":"Nyoro", "french":"nyoro", "german":"Nyoro-Sprache", "iso2":"nyo" },
            { "english":"Nzima", "french":"nzema", "german":"Nzima-Sprache", "iso2":"nzi" },
            { "english":"Occitan (post 1500)", "french":"occitan (après 1500)", "german":"Okzitanisch", "iso2":"oci", "iso1":"oc" },
            { "english":"Ojibwa", "french":"ojibwa", "german":"Ojibwa-Sprache", "iso2":"oji", "iso1":"oj", "iso2b":"oji", "iso3":"oji" },
            { "english":"Oriya", "french":"oriya", "german":"Oriya-Sprache", "iso2":"ori", "iso1":"or", "iso2b":"ori", "iso3":"ori" },
            { "english":"Oromo", "french":"galla", "german":"Galla-Sprache", "iso2":"orm", "iso1":"om", "iso2b":"orm", "iso3":"orm" },
            { "english":"Osage", "french":"osage", "german":"Osage-Sprache", "iso2":"osa" },
            { "english":"Ossetian", "french":"ossète", "german":"Ossetisch", "iso2":"oss", "iso1":"os" },
            { "english":"Turkish, Ottoman (1500-1928)", "french":"turc ottoman (1500-1928)", "german":"Osmanisch", "iso2":"ota" },
            { "english":"Otomian languages", "french":"otomi, langues", "german":"Otomangue-Sprachen", "iso2":"oto" },
            { "english":"Papuan languages", "french":"papoues, langues", "german":"Papuasprachen (Andere)", "iso2":"paa" },
            { "english":"Pangasinan", "french":"pangasinan", "german":"Pangasinan-Sprache", "iso2":"pag" },
            { "english":"Pahlavi", "french":"pahlavi", "german":"Mittelpersisch", "iso2":"pal" },
            { "english":"Pampanga", "french":"pampangan", "german":"Pampanggan-Sprache", "iso2":"pam" },
            { "english":"Panjabi", "french":"pendjabi", "german":"Pandschabi-Sprache", "iso2":"pan", "iso1":"pa" },
            { "english":"Papiamento", "french":"papiamento", "german":"Papiamento", "iso2":"pap" },
            { "english":"Palauan", "french":"palau", "german":"Palau-Sprache", "iso2":"pau" },
            { "english":"Persian, Old (ca.600-400 B.C.)", "french":"perse, vieux (ca. 600-400 av. J.-C.)", "german":"Altpersisch", "iso2":"peo" },
            { "english":"Persian", "french":"persan", "german":"Persisch", "iso2":"fas", "iso1":"fa" },
            { "english":"Philippine languages", "french":"philippines, langues", "german":"Philippinisch-Austronesisch (Andere)", "iso2":"phi" },
            { "english":"Phoenician", "french":"phénicien", "german":"Phönikisch", "iso2":"phn" },
            { "english":"Pali", "french":"pali", "german":"Pali", "iso2":"pli", "iso1":"pi", "iso2b":"pli", "iso3":"pli" },
            { "english":"Polish", "french":"polonais", "german":"Polnisch", "iso2":"pol", "iso1":"pl", "iso2b":"pol", "iso3":"pol" },
            { "english":"Pohnpeian", "french":"pohnpei", "german":"Ponapeanisch", "iso2":"pon" },
            { "english":"Portuguese", "french":"portugais", "german":"Portugiesisch", "iso2":"por", "iso1":"pt", "iso2b":"por", "iso3":"por" },
            { "english":"Prakrit languages", "french":"prâkrit, langues", "german":"Prakrit", "iso2":"pra" },
            { "english":"Provençal, Old (to 1500)", "french":"provençal ancien (jusqu'à 1500)", "german":"Altokzitanisch", "iso2":"pro" },
            { "english":"Pushto", "french":"pachto", "german":"Paschtu", "iso2":"pus", "iso1":"ps" },
            { "english":"Quechua", "french":"quechua", "german":"Quechua-Sprache", "iso2":"que", "iso1":"qu", "iso2b":"que", "iso3":"que" },
            { "english":"Rajasthani", "french":"rajasthani", "german":"Rajasthani", "iso2":"raj" },
            { "english":"Rapanui", "french":"rapanui", "german":"Osterinsel-Sprache", "iso2":"rap" },
            { "english":"Rarotongan", "french":"rarotonga", "german":"Rarotonganisch", "iso2":"rar" },
            { "english":"Romance languages", "french":"romanes, langues", "german":"Romanische Sprachen (Andere)", "iso2":"roa" },
            { "english":"Romansh", "french":"romanche", "german":"Rätoromanisch", "iso2":"roh", "iso1":"rm", "iso2b":"roh", "iso3":"roh" },
            { "english":"Romany", "french":"tsigane", "german":"Romani (Sprache)", "iso2":"rom" },
            { "english":"Romanian", "french":"roumain", "german":"Rumänisch", "iso2":"ron", "iso1":"ro" },
            { "english":"Romanian", "french":"roumain", "german":"Rumänisch", "iso2":"ron", "iso1":"ro" },
            { "english":"Rundi", "french":"rundi", "german":"Rundi-Sprache", "iso2":"run", "iso1":"rn", "iso2b":"run", "iso3":"run" },
            { "english":"Aromanian", "french":"aroumain", "german":"Aromunisch", "iso2":"rup" },
            { "english":"Russian", "french":"russe", "german":"Russisch", "iso2":"rus", "iso1":"ru", "iso2b":"rus", "iso3":"rus" },
            { "english":"Sandawe", "french":"sandawe", "german":"Sandawe-Sprache", "iso2":"sad" },
            { "english":"Sango", "french":"sango", "german":"Sango-Sprache", "iso2":"sag", "iso1":"sg", "iso2b":"sag", "iso3":"sag" },
            { "english":"Yakut", "french":"iakoute", "german":"Jakutisch", "iso2":"sah" },
            { "english":"South American Indian languages", "french":"sud-amérindiennes, langues", "german":"Indianersprachen, Südamerika (Andere)", "iso2":"sai" },
            { "english":"Salishan languages", "french":"salishennes, langues", "german":"Salish-Sprache", "iso2":"sal" },
            { "english":"Samaritan Aramaic", "french":"samaritain", "german":"Samaritanisch", "iso2":"sam" },
            { "english":"Sanskrit", "french":"sanskrit", "german":"Sanskrit", "iso2":"san", "iso1":"sa", "iso2b":"san", "iso3":"san" },
            { "english":"Sasak", "french":"sasak", "german":"Sasak", "iso2":"sas" },
            { "english":"Santali", "french":"santal", "german":"Santali", "iso2":"sat" },
            { "english":"Sicilian", "french":"sicilien", "german":"Sizilianisch", "iso2":"scn" },
            { "english":"Scots", "french":"écossais", "german":"Schottisch", "iso2":"sco" },
            { "english":"Selkup", "french":"selkoupe", "german":"Selkupisch", "iso2":"sel" },
            { "english":"Semitic languages", "french":"sémitiques, langues", "german":"Semitische Sprachen (Andere)", "iso2":"sem" },
            { "english":"Irish, Old (to 900)", "french":"irlandais ancien (jusqu'à 900)", "german":"Altirisch", "iso2":"sga" },
            { "english":"Sign Languages", "french":"langues des signes", "german":"Zeichensprachen", "iso2":"sgn" },
            { "english":"Shan", "french":"chan", "german":"Schan-Sprache", "iso2":"shn" },
            { "english":"Sidamo", "french":"sidamo", "german":"Sidamo-Sprache", "iso2":"sid" },
            { "english":"Sinhala", "french":"singhalais", "german":"Singhalesisch", "iso2":"sin", "iso1":"si" },
            { "english":"Siouan languages", "french":"sioux, langues", "german":"Sioux-Sprachen (Andere)", "iso2":"sio" },
            { "english":"Sino-Tibetan languages", "french":"sino-tibétaines, langues", "german":"Sinotibetische Sprachen (Andere)", "iso2":"sit" },
            { "english":"Slavic languages", "french":"slaves, langues", "german":"Slawische Sprachen (Andere)", "iso2":"sla" },
            { "english":"Slovak", "french":"slovaque", "german":"Slowakisch", "iso2":"slk", "iso1":"sk", "iso2b":"slk", "iso3":"slo" },
            { "english":"Slovak", "french":"slovaque", "german":"Slowakisch", "iso2":"slk", "iso1":"sk" },
            { "english":"Slovenian", "french":"slovène", "german":"Slowenisch", "iso2":"slv", "iso1":"sl", "iso2b":"slv", "iso3":"slv" },
            { "english":"Southern Sami", "french":"sami du Sud", "german":"Südsaamisch", "iso2":"sma" },
            { "english":"Northern Sami", "french":"sami du Nord", "german":"Nordsaamisch", "iso2":"sme", "iso1":"se", "iso2b":"sme", "iso3":"sme" },
            { "english":"Sami languages", "french":"sames, langues", "german":"Saamisch", "iso2":"smi" },
            { "english":"Lule Sami", "french":"sami de Lule", "german":"Lulesaamisch", "iso2":"smj" },
            { "english":"Inari Sami", "french":"sami d'Inari", "german":"Inarisaamisch", "iso2":"smn" },
            { "english":"Samoan", "french":"samoan", "german":"Samoanisch", "iso2":"smo", "iso1":"sm", "iso2b":"smo", "iso3":"smo" },
            { "english":"Skolt Sami", "french":"sami skolt", "german":"Skoltsaamisch", "iso2":"sms" },
            { "english":"Shona", "french":"shona", "german":"Schona-Sprache", "iso2":"sna", "iso1":"sn", "iso2b":"sna", "iso3":"sna" },
            { "english":"Sindhi", "french":"sindhi", "german":"Sindhi-Sprache", "iso2":"snd", "iso1":"sd", "iso2b":"snd", "iso3":"snd" },
            { "english":"Soninke", "french":"soninké", "german":"Soninke-Sprache", "iso2":"snk" },
            { "english":"Sogdian", "french":"sogdien", "german":"Sogdisch", "iso2":"sog" },
            { "english":"Somali", "french":"somali", "german":"Somali", "iso2":"som", "iso1":"so", "iso2b":"som", "iso3":"som" },
            { "english":"Songhai languages", "french":"songhai, langues", "german":"Songhai-Sprache", "iso2":"son" },
            { "english":"Sotho, Southern", "french":"sotho du Sud", "german":"Süd-Sotho-Sprache", "iso2":"sot", "iso1":"st" },
            { "english":"Spanish", "french":"espagnol", "german":"Spanisch", "iso2":"spa", "iso1":"es" },
            { "english":"Albanian", "french":"albanais", "german":"Albanisch", "iso2":"sqi", "iso1":"sq" },
            { "english":"Sardinian", "french":"sarde", "german":"Sardisch", "iso2":"srd", "iso1":"sc", "iso2b":"srd", "iso3":"srd" },
            { "english":"Sranan Tongo", "french":"sranan tongo", "german":"Sranantongo", "iso2":"srn" },
            { "english":"Serbian", "french":"serbe", "german":"Serbisch", "iso2":"srp", "iso1":"sr", "iso2b":"srp", "iso3":"srp" },
            { "english":"Serer", "french":"sérère", "german":"Serer-Sprache", "iso2":"srr" },
            { "english":"Nilo-Saharan languages", "french":"nilo-sahariennes, langues", "german":"Nilosaharanische Sprachen (Andere)", "iso2":"ssa" },
            { "english":"Swati", "french":"swati", "german":"Swasi-Sprache", "iso2":"ssw", "iso1":"ss", "iso2b":"ssw", "iso3":"ssw" },
            { "english":"Sukuma", "french":"sukuma", "german":"Sukuma-Sprache", "iso2":"suk" },
            { "english":"Sundanese", "french":"soundanais", "german":"Sundanesisch", "iso2":"sun", "iso1":"su", "iso2b":"sun", "iso3":"sun" },
            { "english":"Susu", "french":"soussou", "german":"Susu", "iso2":"sus" },
            { "english":"Sumerian", "french":"sumérien", "german":"Sumerisch", "iso2":"sux" },
            { "english":"Swahili", "french":"swahili", "german":"Swahili", "iso2":"swa", "iso1":"sw", "iso2b":"swa", "iso3":"swa" },
            { "english":"Swedish", "french":"suédois", "german":"Schwedisch", "iso2":"swe", "iso1":"sv", "iso2b":"swe", "iso3":"swe" },
            { "english":"Classical Syriac", "french":"syriaque classique", "german":"Syrisch", "iso2":"syc" },
            { "english":"Syriac", "french":"syriaque", "german":"Neuostaramäisch", "iso2":"syr" },
            { "english":"Tahitian", "french":"tahitien", "german":"Tahitisch", "iso2":"tah", "iso1":"ty", "iso2b":"tah", "iso3":"tah" },
            { "english":"Tai languages", "french":"tai, langues", "german":"Thaisprachen (Andere)", "iso2":"tai" },
            { "english":"Tamil", "french":"tamoul", "german":"Tamil", "iso2":"tam", "iso1":"ta", "iso2b":"tam", "iso3":"tam" },
            { "english":"Tatar", "french":"tatar", "german":"Tatarisch", "iso2":"tat", "iso1":"tt", "iso2b":"tat", "iso3":"tat" },
            { "english":"Telugu", "french":"télougou", "german":"Telugu-Sprache", "iso2":"tel", "iso1":"te", "iso2b":"tel", "iso3":"tel" },
            { "english":"Timne", "french":"temne", "german":"Temne-Sprache", "iso2":"tem" },
            { "english":"Tereno", "french":"tereno", "german":"Tereno-Sprache", "iso2":"ter" },
            { "english":"Tetum", "french":"tetum", "german":"Tetum-Sprache", "iso2":"tet" },
            { "english":"Tajik", "french":"tadjik", "german":"Tadschikisch", "iso2":"tgk", "iso1":"tg", "iso2b":"tgk", "iso3":"tgk" },
            { "english":"Tagalog", "french":"tagalog", "german":"Tagalog", "iso2":"tgl", "iso1":"tl", "iso2b":"tgl", "iso3":"tgl" },
            { "english":"Thai", "french":"thaï", "german":"Thailändisch", "iso2":"tha", "iso1":"th", "iso2b":"tha", "iso3":"tha" },
            { "english":"Tibetan", "french":"tibétain", "german":"Tibetisch", "iso2":"bod", "iso1":"bo" },
            { "english":"Tigre", "french":"tigré", "german":"Tigre-Sprache", "iso2":"tig" },
            { "english":"Tigrinya", "french":"tigrigna", "german":"Tigrinja-Sprache", "iso2":"tir", "iso1":"ti", "iso2b":"tir", "iso3":"tir" },
            { "english":"Tiv", "french":"tiv", "german":"Tiv-Sprache", "iso2":"tiv" },
            { "english":"Tokelau", "french":"tokelau", "german":"Tokelauanisch", "iso2":"tkl" },
            { "english":"Klingon", "french":"klingon", "german":"Klingonisch", "iso2":"tlh" },
            { "english":"Tlingit", "french":"tlingit", "german":"Tlingit-Sprache", "iso2":"tli" },
            { "english":"Tamashek", "french":"tamacheq", "german":"Tamaeq", "iso2":"tmh" },
            { "english":"Tonga (Nyasa)", "french":"tonga (Nyasa)", "german":"Tonga (Bantusprache, Sambia)", "iso2":"tog" },
            { "english":"Tonga (Tonga Islands)", "french":"tongan (Îles Tonga)", "german":"Tongaisch", "iso2":"ton", "iso1":"to", "iso2b":"ton", "iso3":"ton" },
            { "english":"Tok Pisin", "french":"tok pisin", "german":"Neumelanesisch", "iso2":"tpi" },
            { "english":"Tsimshian", "french":"tsimshian", "german":"Tsimshian-Sprache", "iso2":"tsi" },
            { "english":"Tswana", "french":"tswana", "german":"Tswana-Sprache", "iso2":"tsn", "iso1":"tn", "iso2b":"tsn", "iso3":"tsn" },
            { "english":"Tsonga", "french":"tsonga", "german":"Tsonga-Sprache", "iso2":"tso", "iso1":"ts", "iso2b":"tso", "iso3":"tso" },
            { "english":"Turkmen", "french":"turkmène", "german":"Turkmenisch", "iso2":"tuk", "iso1":"tk", "iso2b":"tuk", "iso3":"tuk" },
            { "english":"Tumbuka", "french":"tumbuka", "german":"Tumbuka-Sprache", "iso2":"tum" },
            { "english":"Tupi languages", "french":"tupi, langues", "german":"Tupi-Sprache", "iso2":"tup" },
            { "english":"Turkish", "french":"turc", "german":"Türkisch", "iso2":"tur", "iso1":"tr", "iso2b":"tur", "iso3":"tur" },
            { "english":"Altaic languages", "french":"altaïques, langues", "german":"Altaische Sprachen (Andere)", "iso2":"tut" },
            { "english":"Tuvalu", "french":"tuvalu", "german":"Elliceanisch", "iso2":"tvl" },
            { "english":"Twi", "french":"twi", "german":"Twi-Sprache", "iso2":"twi", "iso1":"tw", "iso2b":"twi", "iso3":"twi" },
            { "english":"Tuvinian", "french":"touva", "german":"Tuwinisch", "iso2":"tyv" },
            { "english":"Udmurt", "french":"oudmourte", "german":"Udmurtisch", "iso2":"udm" },
            { "english":"Ugaritic", "french":"ougaritique", "german":"Ugaritisch", "iso2":"uga" },
            { "english":"Uighur", "french":"ouïgour", "german":"Uigurisch", "iso2":"uig", "iso1":"ug" },
            { "english":"Ukrainian", "french":"ukrainien", "german":"Ukrainisch", "iso2":"ukr", "iso1":"uk", "iso2b":"ukr", "iso3":"ukr" },
            { "english":"Umbundu", "french":"umbundu", "german":"Mbundu-Sprache", "iso2":"umb" },
            { "english":"Undetermined", "french":"indéterminée", "german":"Nicht zu entscheiden", "iso2":"und" },
            { "english":"Urdu", "french":"ourdou", "german":"Urdu", "iso2":"urd", "iso1":"ur", "iso2b":"urd", "iso3":"urd" },
            { "english":"Uzbek", "french":"ouszbek", "german":"Usbekisch", "iso2":"uzb", "iso1":"uz", "iso2b":"uzb", "iso3":"uzb" },
            { "english":"Vai", "french":"vaï", "german":"Vai-Sprache", "iso2":"vai" },
            { "english":"Venda", "french":"venda", "german":"Venda-Sprache", "iso2":"ven", "iso1":"ve", "iso2b":"ven", "iso3":"ven" },
            { "english":"Vietnamese", "french":"vietnamien", "german":"Vietnamesisch", "iso2":"vie", "iso1":"vi", "iso2b":"vie", "iso3":"vie" },
            { "english":"Volapük", "french":"volapük", "german":"Volapük", "iso2":"vol", "iso1":"vo", "iso2b":"vol", "iso3":"vol" },
            { "english":"Votic", "french":"vote", "german":"Wotisch", "iso2":"vot" },
            { "english":"Wakashan languages", "french":"wakashanes, langues", "german":"Wakash-Sprachen", "iso2":"wak" },
            { "english":"Wolaitta", "french":"wolaitta", "german":"Walamo-Sprache", "iso2":"wal" },
            { "english":"Waray", "french":"waray", "german":"Waray", "iso2":"war" },
            { "english":"Washo", "french":"washo", "german":"Washo-Sprache", "iso2":"was" },
            { "english":"Welsh", "french":"gallois", "german":"Kymrisch", "iso2":"cym", "iso1":"cy" },
            { "english":"Sorbian languages", "french":"sorabes, langues", "german":"Sorbisch (Andere)", "iso2":"wen" },
            { "english":"Walloon", "french":"wallon", "german":"Wallonisch", "iso2":"wln", "iso1":"wa", "iso2b":"wln", "iso3":"wln" },
            { "english":"Wolof", "french":"wolof", "german":"Wolof-Sprache", "iso2":"wol", "iso1":"wo", "iso2b":"wol", "iso3":"wol" },
            { "english":"Kalmyk", "french":"kalmouk", "german":"Kalmückisch", "iso2":"xal" },
            { "english":"Xhosa", "french":"xhosa", "german":"Xhosa-Sprache", "iso2":"xho", "iso1":"xh", "iso2b":"xho", "iso3":"xho" },
            { "english":"Yao", "french":"yao", "german":"Yao-Sprache (Bantusprache)", "iso2":"yao" },
            { "english":"Yapese", "french":"yapois", "german":"Yapesisch", "iso2":"yap" },
            { "english":"Yiddish", "french":"yiddish", "german":"Jiddisch", "iso2":"yid", "iso1":"yi", "iso2b":"yid", "iso3":"yid" },
            { "english":"Yoruba", "french":"yoruba", "german":"Yoruba-Sprache", "iso2":"yor", "iso1":"yo", "iso2b":"yor", "iso3":"yor" },
            { "english":"Yupik languages", "french":"yupik, langues", "german":"Ypik-Sprachen", "iso2":"ypk" },
            { "english":"Zapotec", "french":"zapotèque", "german":"Zapotekisch", "iso2":"zap" },
            { "english":"Blissymbols", "french":"symboles Bliss", "german":"Bliss-Symbol", "iso2":"zbl" },
            { "english":"Zenaga", "french":"zenaga", "german":"Zenaga", "iso2":"zen" },
            { "english":"Standard Moroccan Tamazight", "french":"amazighe standard marocain", "german":"Standard-marokkanischen Tamazight", "iso2":"zgh" },
            { "english":"Zhuang", "french":"zhuang", "german":"Zhuang", "iso2":"zha", "iso1":"za" },
            { "english":"Chinese", "french":"chinois", "german":"Chinesisch", "iso2":"zho", "iso1":"zh" },
            { "english":"Zande languages", "french":"zandé, langues", "german":"Zande-Sprachen", "iso2":"znd" },
            { "english":"Zulu", "french":"zoulou", "german":"Zulu-Sprache", "iso2":"zul", "iso1":"zu", "iso2b":"zul", "iso3":"zul" },
            { "english":"Zuni", "french":"zuni", "german":"Zuñi-Sprache", "iso2":"zun" },
            { "english":"No linguistic content", "french":"pas de contenu linguistique", "german":"Kein linguistischer Inhalt", "iso2":"zxx" },
            { "english":"Zaza", "french":"zaza", "german":"Zazaki", "iso2":"zza" }
        ];
    }


 }