/**
 * Helper class for Languages
 * @name Language
 * @revision 2
 * @minimumVersion 1.0.0.0
 */
 export class Language
 {    

    findLanguage(language)
    {
        if(!language)
            return language;

        let ll = language.toLocaleLowerCase();

        let lang = this.Languages.filter(x => x.iso1 === ll || x.iso2 === ll || x.english?.toLocaleLowerCase() === ll || x.french?.toLocaleLowerCase() === ll || x.german?.toLocaleLowerCase() === ll);
        if(!lang.length){
            Logger.WLog('Failed to locate language: ' + language);
            return null;
        }
        lang = lang[0];
        Logger.DLog('Found language for ' + language, lang);
        return lang;
    }
    /**
     * Gets the english name for a language
     * @param {string} language the language to lookup
     * @returns the english name, if not known will return the original name
     */
    getEnglishFor(language){        
        
        let lang = this.findLanguage(language);
        if(lang?.english?.length) return lang.english;             
        return language;
    }
    
    /**
     * Gets the ISO-639-1 code for a language
     * @param {string} language the language to lookup
     * @returns the ISO-639-1 code, if not known will return the original name
     */
    getIso1Code(language) {
        let lang = this.findLanguage(language);
        if(lang?.iso1?.length) return lang.iso1;        
        return language;
    }
    
    /**
     * Gets the ISO-639-2 code for a language
     * @param {string} language the language to lookup
     * @returns the ISO-639-2 code, if not known will return the original name
     */
    getIso2Code(language) {
        let lang = this.findLanguage(language);
        if(lang?.iso2?.length) return lang.iso2;     
        return language;
    }

    constructor()
    {
        this.Languages = [
            {english:"Afar",french:"afar",german:"Danakil-Sprache",iso2:"aar",iso1:"aa"},
            {english:"Abkhazian",french:"abkhaze",german:"Abchasisch",iso2:"abk",iso1:"ab"},
            {english:"Achinese",french:"aceh",german:"Aceh-Sprache",iso2:"ace"},
            {english:"Acoli",french:"acoli",german:"Acholi-Sprache",iso2:"ach"},
            {english:"Adangme",french:"adangme",german:"Adangme-Sprache",iso2:"ada"},
            {english:"Adyghe",french:"adygh\u00E9",german:"Adygisch",iso2:"ady"},
            {english:"Afro-Asiatic languages",french:"afro-asiatiques, langues",german:"Hamitosemitische Sprachen (Andere)",iso2:"afa"},
            {english:"Afrihili",french:"afrihili",german:"Afrihili",iso2:"afh"},
            {english:"Afrikaans",french:"afrikaans",german:"Afrikaans",iso2:"afr",iso1:"af"},
            {english:"Ainu",french:"a\u00EFnou",german:"Ainu-Sprache",iso2:"ain"},
            {english:"Akan",french:"akan",german:"Akan-Sprache",iso2:"aka",iso1:"ak"},
            {english:"Akkadian",french:"akkadien",german:"Akkadisch",iso2:"akk"},
            {english:"Albanian",french:"albanais",german:"Albanisch",iso2:"sqi",iso1:"sq"},
            {english:"Aleut",french:"al\u00E9oute",german:"Aleutisch",iso2:"ale"},
            {english:"Algonquian languages",french:"algonquines, langues",german:"Algonkin-Sprachen (Andere)",iso2:"alg"},
            {english:"Southern Altai",french:"altai du Sud",german:"Altaisch",iso2:"alt"},
            {english:"Amharic",french:"amharique",german:"Amharisch",iso2:"amh",iso1:"am"},
            {english:"English, Old (ca.450-1100)",french:"anglo-saxon (ca.450-1100)",german:"Altenglisch",iso2:"ang"},
            {english:"Angika",french:"angika",german:"Anga-Sprache",iso2:"anp"},
            {english:"Apache languages",french:"apaches, langues",german:"Apachen-Sprachen",iso2:"apa"},
            {english:"Arabic",french:"arabe",german:"Arabisch",iso2:"ara",iso1:"ar"},
            {english:"Official Aramaic (700-300 BCE)",french:"aram\u00E9en d\u0027empire (700-300 BCE)",german:"Aram\u00E4isch",iso2:"arc"},
            {english:"Aragonese",french:"aragonais",german:"Aragonesisch",iso2:"arg",iso1:"an"},
            {english:"Armenian",french:"arm\u00E9nien",german:"Armenisch",iso2:"hye",iso1:"hy"},
            {english:"Mapudungun",french:"mapudungun",german:"Arauka-Sprachen",iso2:"arn"},
            {english:"Arapaho",french:"arapaho",german:"Arapaho-Sprache",iso2:"arp"},
            {english:"Artificial languages",french:"artificielles, langues",german:"Kunstsprachen (Andere)",iso2:"art"},
            {english:"Arawak",french:"arawak",german:"Arawak-Sprachen",iso2:"arw"},
            {english:"Assamese",french:"assamais",german:"Assamesisch",iso2:"asm",iso1:"as"},
            {english:"Asturian",french:"asturien",german:"Asturisch",iso2:"ast"},
            {english:"Athapascan languages",french:"athapascanes, langues",german:"Athapaskische Sprachen (Andere)",iso2:"ath"},
            {english:"Australian languages",french:"australiennes, langues",german:"Australische Sprachen",iso2:"aus"},
            {english:"Avaric",french:"avar",german:"Awarisch",iso2:"ava",iso1:"av"},
            {english:"Avestan",french:"avestique",german:"Avestisch",iso2:"ave",iso1:"ae"},
            {english:"Awadhi",french:"awadhi",german:"Awadhi",iso2:"awa"},
            {english:"Aymara",french:"aymara",german:"Aymar\u00E1-Sprache",iso2:"aym",iso1:"ay"},
            {english:"Azerbaijani",french:"az\u00E9ri",german:"Aserbeidschanisch",iso2:"aze",iso1:"az"},
            {english:"Banda languages",french:"banda, langues",german:"Banda-Sprachen (Ubangi-Sprachen)",iso2:"bad"},
            {english:"Bamileke languages",french:"bamil\u00E9k\u00E9, langues",german:"Bamileke-Sprachen",iso2:"bai"},
            {english:"Bashkir",french:"bachkir",german:"Baschkirisch",iso2:"bak",iso1:"ba"},
            {english:"Baluchi",french:"baloutchi",german:"Belutschisch",iso2:"bal"},
            {english:"Bambara",french:"bambara",german:"Bambara-Sprache",iso2:"bam",iso1:"bm"},
            {english:"Balinese",french:"balinais",german:"Balinesisch",iso2:"ban"},
            {english:"Basque",french:"basque",german:"Baskisch",iso2:"eus",iso1:"eu"},
            {english:"Basa",french:"basa",german:"Basaa-Sprache",iso2:"bas"},
            {english:"Baltic languages",french:"baltes, langues",german:"Baltische Sprachen (Andere)",iso2:"bat"},
            {english:"Beja",french:"bedja",german:"Bedauye",iso2:"bej"},
            {english:"Belarusian",french:"bi\u00E9lorusse",german:"Wei\u00DFrussisch",iso2:"bel",iso1:"be"},
            {english:"Bemba",french:"bemba",german:"Bemba-Sprache",iso2:"bem"},
            {english:"Bengali",french:"bengali",german:"Bengali",iso2:"ben",iso1:"bn"},
            {english:"Berber languages",french:"berb\u00E8res, langues",german:"Berbersprachen (Andere)",iso2:"ber"},
            {english:"Bhojpuri",french:"bhojpuri",german:"Bhojpuri",iso2:"bho"},
            {english:"Bihari languages",french:"langues biharis",german:"Bihari (Andere)",iso2:"bih",iso1:"bh"},
            {english:"Bikol",french:"bikol",german:"Bikol-Sprache",iso2:"bik"},
            {english:"Bini",french:"bini",german:"Edo-Sprache",iso2:"bin"},
            {english:"Bislama",french:"bichlamar",german:"Beach-la-mar",iso2:"bis",iso1:"bi"},
            {english:"Siksika",french:"blackfoot",german:"Blackfoot-Sprache",iso2:"bla"},
            {english:"Bantu languages",french:"bantou, langues",german:"Bantusprachen (Andere)",iso2:"bnt"},
            {english:"Tibetan",french:"tib\u00E9tain",german:"Tibetisch",iso2:"bod",iso1:"bo"},
            {english:"Bosnian",french:"bosniaque",german:"Bosnisch",iso2:"bos",iso1:"bs"},
            {english:"Braj",french:"braj",german:"Braj-Bhakha",iso2:"bra"},
            {english:"Breton",french:"breton",german:"Bretonisch",iso2:"bre",iso1:"br"},
            {english:"Batak languages",french:"batak, langues",german:"Batak-Sprache",iso2:"btk"},
            {english:"Buriat",french:"bouriate",german:"Burjatisch",iso2:"bua"},
            {english:"Buginese",french:"bugi",german:"Bugi-Sprache",iso2:"bug"},
            {english:"Bulgarian",french:"bulgare",german:"Bulgarisch",iso2:"bul",iso1:"bg"},
            {english:"Burmese",french:"birman",german:"Birmanisch",iso2:"mya",iso1:"my"},
            {english:"Blin",french:"blin",german:"Bilin-Sprache",iso2:"byn"},
            {english:"Caddo",french:"caddo",german:"Caddo-Sprachen",iso2:"cad"},
            {english:"Central American Indian languages",french:"am\u00E9rindiennes de l\u0027Am\u00E9rique centrale,  langues",german:"Indianersprachen, Zentralamerika (Andere)",iso2:"cai"},
            {english:"Galibi Carib",french:"karib",german:"Karibische Sprachen",iso2:"car"},
            {english:"Catalan",french:"catalan",german:"Katalanisch",iso2:"cat",iso1:"ca"},
            {english:"Caucasian languages",french:"caucasiennes, langues",german:"Kaukasische Sprachen (Andere)",iso2:"cau"},
            {english:"Cebuano",french:"cebuano",german:"Cebuano",iso2:"ceb"},
            {english:"Celtic languages",french:"celtiques, langues",german:"Keltische Sprachen (Andere)",iso2:"cel"},
            {english:"Czech",french:"tch\u00E8que",german:"Tschechisch",iso2:"ces",iso1:"cs"},
            {english:"Chamorro",french:"chamorro",german:"Chamorro-Sprache",iso2:"cha",iso1:"ch"},
            {english:"Chibcha",french:"chibcha",german:"Chibcha-Sprachen",iso2:"chb"},
            {english:"Chechen",french:"tch\u00E9tch\u00E8ne",german:"Tschetschenisch",iso2:"che",iso1:"ce"},
            {english:"Chagatai",french:"djaghata\u00EF",german:"Tschagataisch",iso2:"chg"},
            {english:"Chinese",french:"chinois",german:"Chinesisch",iso2:"zho",iso1:"zh"},
            {english:"Chuukese",french:"chuuk",german:"Trukesisch",iso2:"chk"},
            {english:"Mari",french:"mari",german:"Tscheremissisch",iso2:"chm"},
            {english:"Chinook jargon",french:"chinook, jargon",german:"Chinook-Jargon",iso2:"chn"},
            {english:"Choctaw",french:"choctaw",german:"Choctaw-Sprache",iso2:"cho"},
            {english:"Chipewyan",french:"chipewyan",german:"Chipewyan-Sprache",iso2:"chp"},
            {english:"Cherokee",french:"cherokee",german:"Cherokee-Sprache",iso2:"chr"},
            {english:"Church Slavic",french:"slavon d\u0027\u00E9glise",german:"Kirchenslawisch",iso2:"chu",iso1:"cu"},
            {english:"Chuvash",french:"tchouvache",german:"Tschuwaschisch",iso2:"chv",iso1:"cv"},
            {english:"Cheyenne",french:"cheyenne",german:"Cheyenne-Sprache",iso2:"chy"},
            {english:"Chamic languages",french:"chames, langues",german:"Cham-Sprachen",iso2:"cmc"},
            {english:"Coptic",french:"copte",german:"Koptisch",iso2:"cop"},
            {english:"Cornish",french:"cornique",german:"Kornisch",iso2:"cor",iso1:"kw"},
            {english:"Corsican",french:"corse",german:"Korsisch",iso2:"cos",iso1:"co"},
            {english:"Creoles and pidgins, English based",french:"cr\u00E9oles et pidgins bas\u00E9s sur l\u0027anglais",german:"Kreolisch-Englisch (Andere)",iso2:"cpe"},
            {english:"Creoles and pidgins, French-based",french:"cr\u00E9oles et pidgins bas\u00E9s sur le fran\u00E7ais",german:"Kreolisch-Franz\u00F6sisch (Andere)",iso2:"cpf"},
            {english:"Creoles and pidgins, Portuguese-based",french:"cr\u00E9oles et pidgins bas\u00E9s sur le portugais",german:"Kreolisch-Portugiesisch (Andere)",iso2:"cpp"},
            {english:"Cree",french:"cree",german:"Cree-Sprache",iso2:"cre",iso1:"cr"},
            {english:"Crimean Tatar",french:"tatar de Crim\u00E9",german:"Krimtatarisch",iso2:"crh"},
            {english:"Creoles and pidgins",french:"cr\u00E9oles et pidgins",german:"Kreolische Sprachen",iso2:"crp"},
            {english:"Kashubian",french:"kachoube",german:"Kaschubisch",iso2:"csb"},
            {english:"Cushitic languages",french:"couchitiques,  langues",german:"Kuschitische Sprachen (Andere)",iso2:"cus"},
            {english:"Welsh",french:"gallois",german:"Kymrisch",iso2:"cym",iso1:"cy"},
            {english:"Czech",french:"tch\u00E8que",german:"Tschechisch",iso2:"ces",iso1:"cs"},
            {english:"Dakota",french:"dakota",german:"Dakota-Sprache",iso2:"dak"},
            {english:"Danish",french:"danois",german:"D\u00E4nisch",iso2:"dan",iso1:"da"},
            {english:"Dargwa",french:"dargwa",german:"Darginisch",iso2:"dar"},
            {english:"Land Dayak languages",french:"dayak, langues",german:"Dajakisch",iso2:"day"},
            {english:"Delaware",french:"delaware",german:"Delaware-Sprache",iso2:"del"},
            {english:"Slave (Athapascan)",french:"esclave (athapascan)",german:"Slave-Sprache",iso2:"den"},
            {english:"German",french:"allemand",german:"Deutsch",iso2:"deu",iso1:"de"},
            {english:"Dogrib",french:"dogrib",german:"Dogrib-Sprache",iso2:"dgr"},
            {english:"Dinka",french:"dinka",german:"Dinka-Sprache",iso2:"din"},
            {english:"Divehi",french:"maldivien",german:"Maledivisch",iso2:"div",iso1:"dv"},
            {english:"Dogri",french:"dogri",german:"Dogri",iso2:"doi"},
            {english:"Dravidian languages",french:"dravidiennes,  langues",german:"Drawidische Sprachen (Andere)",iso2:"dra"},
            {english:"Lower Sorbian",french:"bas-sorabe",german:"Niedersorbisch",iso2:"dsb"},
            {english:"Duala",french:"douala",german:"Duala-Sprachen",iso2:"dua"},
            {english:"Dutch, Middle (ca.1050-1350)",french:"n\u00E9erlandais moyen (ca. 1050-1350)",german:"Mittelniederl\u00E4ndisch",iso2:"dum"},
            {english:"Dutch",french:"n\u00E9erlandais",german:"Niederl\u00E4ndisch",iso2:"nld",iso1:"nl"},
            {english:"Dyula",french:"dioula",german:"Dyula-Sprache",iso2:"dyu"},
            {english:"Dzongkha",french:"dzongkha",german:"Dzongkha",iso2:"dzo",iso1:"dz"},
            {english:"Efik",french:"efik",german:"Efik",iso2:"efi"},
            {english:"Egyptian (Ancient)",french:"\u00E9gyptien",german:"\u00C4gyptisch",iso2:"egy"},
            {english:"Ekajuk",french:"ekajuk",german:"Ekajuk",iso2:"eka"},
            {english:"Greek, Modern (1453-)",french:"grec moderne (apr\u00E8s 1453)",german:"Neugriechisch",iso2:"ell",iso1:"el"},
            {english:"Elamite",french:"\u00E9lamite",german:"Elamisch",iso2:"elx"},
            {english:"English",french:"anglais",german:"Englisch",iso2:"eng",iso1:"en"},
            {english:"English, Middle (1100-1500)",french:"anglais moyen (1100-1500)",german:"Mittelenglisch",iso2:"enm"},
            {english:"Esperanto",french:"esp\u00E9ranto",german:"Esperanto",iso2:"epo",iso1:"eo"},
            {english:"Estonian",french:"estonien",german:"Estnisch",iso2:"est",iso1:"et"},
            {english:"Basque",french:"basque",german:"Baskisch",iso2:"eus",iso1:"eu"},
            {english:"Ewe",french:"\u00E9w\u00E9",german:"Ewe-Sprache",iso2:"ewe",iso1:"ee"},
            {english:"Ewondo",french:"\u00E9wondo",german:"Ewondo",iso2:"ewo"},
            {english:"Fang",french:"fang",german:"Pangwe-Sprache",iso2:"fan"},
            {english:"Faroese",french:"f\u00E9ro\u00EFen",german:"F\u00E4r\u00F6isch",iso2:"fao",iso1:"fo"},
            {english:"Persian",french:"persan",german:"Persisch",iso2:"fas",iso1:"fa"},
            {english:"Fanti",french:"fanti",german:"Fante-Sprache",iso2:"fat"},
            {english:"Fijian",french:"fidjien",german:"Fidschi-Sprache",iso2:"fij",iso1:"fj"},
            {english:"Filipino",french:"filipino",german:"Pilipino",iso2:"fil"},
            {english:"Finnish",french:"finnois",german:"Finnisch",iso2:"fin",iso1:"fi"},
            {english:"Finno-Ugrian languages",french:"finno-ougriennes,  langues",german:"Finnougrische Sprachen (Andere)",iso2:"fiu"},
            {english:"Fon",french:"fon",german:"Fon-Sprache",iso2:"fon"},
            {english:"French",french:"fran\u00E7ais",german:"Franz\u00F6sisch",iso2:"fra",iso1:"fr"},
            {english:"French",french:"fran\u00E7ais",german:"Franz\u00F6sisch",iso2:"fra",iso1:"fr"},
            {english:"French, Middle (ca.1400-1600)",french:"fran\u00E7ais moyen (1400-1600)",german:"Mittelfranz\u00F6sisch",iso2:"frm"},
            {english:"French, Old (842-ca.1400)",french:"fran\u00E7ais ancien (842-ca.1400)",german:"Altfranz\u00F6sisch",iso2:"fro"},
            {english:"Northern Frisian",french:"frison septentrional",german:"Nordfriesisch",iso2:"frr"},
            {english:"Eastern Frisian",french:"frison oriental",german:"Ostfriesisch",iso2:"frs"},
            {english:"Western Frisian",french:"frison occidental",german:"Friesisch",iso2:"fry",iso1:"fy"},
            {english:"Fulah",french:"peul",german:"Ful",iso2:"ful",iso1:"ff"},
            {english:"Friulian",french:"frioulan",german:"Friulisch",iso2:"fur"},
            {english:"Ga",french:"ga",german:"Ga-Sprache",iso2:"gaa"},
            {english:"Gayo",french:"gayo",german:"Gayo-Sprache",iso2:"gay"},
            {english:"Gbaya",french:"gbaya",german:"Gbaya-Sprache",iso2:"gba"},
            {english:"Germanic languages",french:"germaniques, langues",german:"Germanische Sprachen (Andere)",iso2:"gem"},
            {english:"Georgian",french:"g\u00E9orgien",german:"Georgisch",iso2:"kat",iso1:"ka"},
            {english:"German",french:"allemand",german:"Deutsch",iso2:"deu",iso1:"de"},
            {english:"Geez",french:"gu\u00E8ze",german:"Alt\u00E4thiopisch",iso2:"gez"},
            {english:"Gilbertese",french:"kiribati",german:"Gilbertesisch",iso2:"gil"},
            {english:"Gaelic",french:"ga\u00E9lique",german:"G\u00E4lisch-Schottisch",iso2:"gla",iso1:"gd"},
            {english:"Irish",french:"irlandais",german:"Irisch",iso2:"gle",iso1:"ga"},
            {english:"Galician",french:"galicien",german:"Galicisch",iso2:"glg",iso1:"gl"},
            {english:"Manx",french:"manx",german:"Manx",iso2:"glv",iso1:"gv"},
            {english:"German, Middle High (ca.1050-1500)",french:"allemand, moyen haut (ca. 1050-1500)",german:"Mittelhochdeutsch",iso2:"gmh"},
            {english:"German, Old High (ca.750-1050)",french:"allemand, vieux haut (ca. 750-1050)",german:"Althochdeutsch",iso2:"goh"},
            {english:"Gondi",french:"gond",german:"Gondi-Sprache",iso2:"gon"},
            {english:"Gorontalo",french:"gorontalo",german:"Gorontalesisch",iso2:"gor"},
            {english:"Gothic",french:"gothique",german:"Gotisch",iso2:"got"},
            {english:"Grebo",french:"grebo",german:"Grebo-Sprache",iso2:"grb"},
            {english:"Greek, Ancient (to 1453)",french:"grec ancien (jusqu\u0027\u00E0 1453)",german:"Griechisch",iso2:"grc"},
            {english:"Greek, Modern (1453-)",french:"grec moderne (apr\u00E8s 1453)",german:"Neugriechisch",iso2:"ell",iso1:"el"},
            {english:"Guarani",french:"guarani",german:"Guaran\u00ED-Sprache",iso2:"grn",iso1:"gn"},
            {english:"Swiss German",french:"suisse al\u00E9manique",german:"Schweizerdeutsch",iso2:"gsw"},
            {english:"Gujarati",french:"goudjrati",german:"Gujarati-Sprache",iso2:"guj",iso1:"gu"},
            {english:"Gwich\u0027in",french:"gwich\u0027in",german:"Kutchin-Sprache",iso2:"gwi"},
            {english:"Haida",french:"haida",german:"Haida-Sprache",iso2:"hai"},
            {english:"Haitian",french:"ha\u00EFtien",german:"Ha\u00EFtien (Haiti-Kreolisch)",iso2:"hat",iso1:"ht"},
            {english:"Hausa",french:"haoussa",german:"Haussa-Sprache",iso2:"hau",iso1:"ha"},
            {english:"Hawaiian",french:"hawa\u00EFen",german:"Hawaiisch",iso2:"haw"},
            {english:"Hebrew",french:"h\u00E9breu",german:"Hebr\u00E4isch",iso2:"heb",iso1:"he"},
            {english:"Herero",french:"herero",german:"Herero-Sprache",iso2:"her",iso1:"hz"},
            {english:"Hiligaynon",french:"hiligaynon",german:"Hiligaynon-Sprache",iso2:"hil"},
            {english:"Himachali languages",french:"langues himachalis",german:"Himachali",iso2:"him"},
            {english:"Hindi",french:"hindi",german:"Hindi",iso2:"hin",iso1:"hi"},
            {english:"Hittite",french:"hittite",german:"Hethitisch",iso2:"hit"},
            {english:"Hmong",french:"hmong",german:"Miao-Sprachen",iso2:"hmn"},
            {english:"Hiri Motu",french:"hiri motu",german:"Hiri-Motu",iso2:"hmo",iso1:"ho"},
            {english:"Croatian",french:"croate",german:"Kroatisch",iso2:"hrv",iso1:"hr"},
            {english:"Upper Sorbian",french:"haut-sorabe",german:"Obersorbisch",iso2:"hsb"},
            {english:"Hungarian",french:"hongrois",german:"Ungarisch",iso2:"hun",iso1:"hu"},
            {english:"Hupa",french:"hupa",german:"Hupa-Sprache",iso2:"hup"},
            {english:"Armenian",french:"arm\u00E9nien",german:"Armenisch",iso2:"hye",iso1:"hy"},
            {english:"Iban",french:"iban",german:"Iban-Sprache",iso2:"iba"},
            {english:"Igbo",french:"igbo",german:"Ibo-Sprache",iso2:"ibo",iso1:"ig"},
            {english:"Icelandic",french:"islandais",german:"Isl\u00E4ndisch",iso2:"isl",iso1:"is"},
            {english:"Ido",french:"ido",german:"Ido",iso2:"ido",iso1:"io"},
            {english:"Sichuan Yi",french:"yi de Sichuan",german:"Lalo-Sprache",iso2:"iii",iso1:"ii"},
            {english:"Ijo languages",french:"ijo, langues",german:"Ijo-Sprache",iso2:"ijo"},
            {english:"Inuktitut",french:"inuktitut",german:"Inuktitut",iso2:"iku",iso1:"iu"},
            {english:"Interlingue",french:"interlingue",german:"Interlingue",iso2:"ile",iso1:"ie"},
            {english:"Iloko",french:"ilocano",german:"Ilokano-Sprache",iso2:"ilo"},
            {english:"Interlingua (International Auxiliary Language Association)",french:"interlingua (langue auxiliaire internationale)",german:"Interlingua",iso2:"ina",iso1:"ia"},
            {english:"Indic languages",french:"indo-aryennes, langues",german:"Indoarische Sprachen (Andere)",iso2:"inc"},
            {english:"Indonesian",french:"indon\u00E9sien",german:"Bahasa Indonesia",iso2:"ind",iso1:"id"},
            {english:"Indo-European languages",french:"indo-europ\u00E9ennes, langues",german:"Indogermanische Sprachen (Andere)",iso2:"ine"},
            {english:"Ingush",french:"ingouche",german:"Inguschisch",iso2:"inh"},
            {english:"Inupiaq",french:"inupiaq",german:"Inupik",iso2:"ipk",iso1:"ik"},
            {english:"Iranian languages",french:"iraniennes, langues",german:"Iranische Sprachen (Andere)",iso2:"ira"},
            {english:"Iroquoian languages",french:"iroquoises, langues",german:"Irokesische Sprachen",iso2:"iro"},
            {english:"Icelandic",french:"islandais",german:"Isl\u00E4ndisch",iso2:"isl",iso1:"is"},
            {english:"Italian",french:"italien",german:"Italienisch",iso2:"ita",iso1:"it"},
            {english:"Javanese",french:"javanais",german:"Javanisch",iso2:"jav",iso1:"jv"},
            {english:"Lojban",french:"lojban",german:"Lojban",iso2:"jbo"},
            {english:"Japanese",french:"japonais",german:"Japanisch",iso2:"jpn",iso1:"ja"},
            {english:"Judeo-Persian",french:"jud\u00E9o-persan",german:"J\u00FCdisch-Persisch",iso2:"jpr"},
            {english:"Judeo-Arabic",french:"jud\u00E9o-arabe",german:"J\u00FCdisch-Arabisch",iso2:"jrb"},
            {english:"Kara-Kalpak",french:"karakalpak",german:"Karakalpakisch",iso2:"kaa"},
            {english:"Kabyle",french:"kabyle",german:"Kabylisch",iso2:"kab"},
            {english:"Kachin",french:"kachin",german:"Kachin-Sprache",iso2:"kac"},
            {english:"Kalaallisut",french:"groenlandais",german:"Gr\u00F6nl\u00E4ndisch",iso2:"kal",iso1:"kl"},
            {english:"Kamba",french:"kamba",german:"Kamba-Sprache",iso2:"kam"},
            {english:"Kannada",french:"kannada",german:"Kannada",iso2:"kan",iso1:"kn"},
            {english:"Karen languages",french:"karen, langues",german:"Karenisch",iso2:"kar"},
            {english:"Kashmiri",french:"kashmiri",german:"Kaschmiri",iso2:"kas",iso1:"ks"},
            {english:"Georgian",french:"g\u00E9orgien",german:"Georgisch",iso2:"kat",iso1:"ka"},
            {english:"Kanuri",french:"kanouri",german:"Kanuri-Sprache",iso2:"kau",iso1:"kr"},
            {english:"Kawi",french:"kawi",german:"Kawi",iso2:"kaw"},
            {english:"Kazakh",french:"kazakh",german:"Kasachisch",iso2:"kaz",iso1:"kk"},
            {english:"Kabardian",french:"kabardien",german:"Kabardinisch",iso2:"kbd"},
            {english:"Khasi",french:"khasi",german:"Khasi-Sprache",iso2:"kha"},
            {english:"Khoisan languages",french:"kho\u00EFsan, langues",german:"Khoisan-Sprachen (Andere)",iso2:"khi"},
            {english:"Central Khmer",french:"khmer central",german:"Kambodschanisch",iso2:"khm",iso1:"km"},
            {english:"Khotanese",french:"khotanais",german:"Sakisch",iso2:"kho"},
            {english:"Kikuyu",french:"kikuyu",german:"Kikuyu-Sprache",iso2:"kik",iso1:"ki"},
            {english:"Kinyarwanda",french:"rwanda",german:"Rwanda-Sprache",iso2:"kin",iso1:"rw"},
            {english:"Kirghiz",french:"kirghiz",german:"Kirgisisch",iso2:"kir",iso1:"ky"},
            {english:"Kimbundu",french:"kimbundu",german:"Kimbundu-Sprache",iso2:"kmb"},
            {english:"Konkani",french:"konkani",german:"Konkani",iso2:"kok"},
            {english:"Komi",french:"kom",german:"Komi-Sprache",iso2:"kom",iso1:"kv"},
            {english:"Kongo",french:"kongo",german:"Kongo-Sprache",iso2:"kon",iso1:"kg"},
            {english:"Korean",french:"cor\u00E9en",german:"Koreanisch",iso2:"kor",iso1:"ko"},
            {english:"Kosraean",french:"kosrae",german:"Kosraeanisch",iso2:"kos"},
            {english:"Kpelle",french:"kpell\u00E9",german:"Kpelle-Sprache",iso2:"kpe"},
            {english:"Karachay-Balkar",french:"karatchai balkar",german:"Karatschaiisch-Balkarisch",iso2:"krc"},
            {english:"Karelian",french:"car\u00E9lien",german:"Karelisch",iso2:"krl"},
            {english:"Kru languages",french:"krou, langues",german:"Kru-Sprachen (Andere)",iso2:"kro"},
            {english:"Kurukh",french:"kurukh",german:"Oraon-Sprache",iso2:"kru"},
            {english:"Kuanyama",french:"kuanyama",german:"Kwanyama-Sprache",iso2:"kua",iso1:"kj"},
            {english:"Kumyk",french:"koumyk",german:"Kum\u00FCkisch",iso2:"kum"},
            {english:"Kurdish",french:"kurde",german:"Kurdisch",iso2:"kur",iso1:"ku"},
            {english:"Kutenai",french:"kutenai",german:"Kutenai-Sprache",iso2:"kut"},
            {english:"Ladino",french:"jud\u00E9o-espagnol",german:"Judenspanisch",iso2:"lad"},
            {english:"Lahnda",french:"lahnda",german:"Lahnda",iso2:"lah"},
            {english:"Lamba",french:"lamba",german:"Lamba-Sprache (Bantusprache)",iso2:"lam"},
            {english:"Lao",french:"lao",german:"Laotisch",iso2:"lao",iso1:"lo"},
            {english:"Latin",french:"latin",german:"Latein",iso2:"lat",iso1:"la"},
            {english:"Latvian",french:"letton",german:"Lettisch",iso2:"lav",iso1:"lv"},
            {english:"Lezghian",french:"lezghien",german:"Lesgisch",iso2:"lez"},
            {english:"Limburgan",french:"limbourgeois",german:"Limburgisch",iso2:"lim",iso1:"li"},
            {english:"Lingala",french:"lingala",german:"Lingala",iso2:"lin",iso1:"ln"},
            {english:"Lithuanian",french:"lituanien",german:"Litauisch",iso2:"lit",iso1:"lt"},
            {english:"Mongo",french:"mongo",german:"Mongo-Sprache",iso2:"lol"},
            {english:"Lozi",french:"lozi",german:"Rotse-Sprache",iso2:"loz"},
            {english:"Luxembourgish",french:"luxembourgeois",german:"Luxemburgisch",iso2:"ltz",iso1:"lb"},
            {english:"Luba-Lulua",french:"luba-lulua",german:"Lulua-Sprache",iso2:"lua"},
            {english:"Luba-Katanga",french:"luba-katanga",german:"Luba-Katanga-Sprache",iso2:"lub",iso1:"lu"},
            {english:"Ganda",french:"ganda",german:"Ganda-Sprache",iso2:"lug",iso1:"lg"},
            {english:"Luiseno",french:"luiseno",german:"Luise\u00F1o-Sprache",iso2:"lui"},
            {english:"Lunda",french:"lunda",german:"Lunda-Sprache",iso2:"lun"},
            {english:"Luo (Kenya and Tanzania)",french:"luo (Kenya et Tanzanie)",german:"Luo-Sprache",iso2:"luo"},
            {english:"Lushai",french:"lushai",german:"Lushai-Sprache",iso2:"lus"},
            {english:"Macedonian",french:"mac\u00E9donien",german:"Makedonisch",iso2:"mkd",iso1:"mk"},
            {english:"Madurese",french:"madourais",german:"Maduresisch",iso2:"mad"},
            {english:"Magahi",french:"magahi",german:"Khotta",iso2:"mag"},
            {english:"Marshallese",french:"marshall",german:"Marschallesisch",iso2:"mah",iso1:"mh"},
            {english:"Maithili",french:"maithili",german:"Maithili",iso2:"mai"},
            {english:"Makasar",french:"makassar",german:"Makassarisch",iso2:"mak"},
            {english:"Malayalam",french:"malayalam",german:"Malayalam",iso2:"mal",iso1:"ml"},
            {english:"Mandingo",french:"mandingue",german:"Malinke-Sprache",iso2:"man"},
            {english:"Maori",french:"maori",german:"Maori-Sprache",iso2:"mri",iso1:"mi"},
            {english:"Austronesian languages",french:"austron\u00E9siennes, langues",german:"Austronesische Sprachen (Andere)",iso2:"map"},
            {english:"Marathi",french:"marathe",german:"Marathi",iso2:"mar",iso1:"mr"},
            {english:"Masai",french:"massa\u00EF",german:"Massai-Sprache",iso2:"mas"},
            {english:"Malay",french:"malais",german:"Malaiisch",iso2:"msa",iso1:"ms"},
            {english:"Moksha",french:"moksa",german:"Mokscha-Sprache",iso2:"mdf"},
            {english:"Mandar",french:"mandar",german:"Mandaresisch",iso2:"mdr"},
            {english:"Mende",french:"mend\u00E9",german:"Mende-Sprache",iso2:"men"},
            {english:"Irish, Middle (900-1200)",french:"irlandais moyen (900-1200)",german:"Mittelirisch",iso2:"mga"},
            {english:"Mi\u0027kmaq",french:"mi\u0027kmaq",german:"Micmac-Sprache",iso2:"mic"},
            {english:"Minangkabau",french:"minangkabau",german:"Minangkabau-Sprache",iso2:"min"},
            {english:"Uncoded languages",french:"langues non cod\u00E9es",german:"Einzelne andere Sprachen",iso2:"mis"},
            {english:"Macedonian",french:"mac\u00E9donien",german:"Makedonisch",iso2:"mkd",iso1:"mk"},
            {english:"Mon-Khmer languages",french:"m\u00F4n-khmer, langues",german:"Mon-Khmer-Sprachen (Andere)",iso2:"mkh"},
            {english:"Malagasy",french:"malgache",german:"Malagassi-Sprache",iso2:"mlg",iso1:"mg"},
            {english:"Maltese",french:"maltais",german:"Maltesisch",iso2:"mlt",iso1:"mt"},
            {english:"Manchu",french:"mandchou",german:"Mandschurisch",iso2:"mnc"},
            {english:"Manipuri",french:"manipuri",german:"Meithei-Sprache",iso2:"mni"},
            {english:"Manobo languages",french:"manobo, langues",german:"Manobo-Sprachen",iso2:"mno"},
            {english:"Mohawk",french:"mohawk",german:"Mohawk-Sprache",iso2:"moh"},
            {english:"Mongolian",french:"mongol",german:"Mongolisch",iso2:"mon",iso1:"mn"},
            {english:"Mossi",french:"mor\u00E9",german:"Mossi-Sprache",iso2:"mos"},
            {english:"Maori",french:"maori",german:"Maori-Sprache",iso2:"mri",iso1:"mi"},
            {english:"Malay",french:"malais",german:"Malaiisch",iso2:"msa",iso1:"ms"},
            {english:"Multiple languages",french:"multilingue",german:"Mehrere Sprachen",iso2:"mul"},
            {english:"Munda languages",french:"mounda, langues",german:"Mundasprachen (Andere)",iso2:"mun"},
            {english:"Creek",french:"muskogee",german:"Muskogisch",iso2:"mus"},
            {english:"Mirandese",french:"mirandais",german:"Mirandesisch",iso2:"mwl"},
            {english:"Marwari",french:"marvari",german:"Marwari",iso2:"mwr"},
            {english:"Burmese",french:"birman",german:"Birmanisch",iso2:"mya",iso1:"my"},
            {english:"Mayan languages",french:"maya, langues",german:"Maya-Sprachen",iso2:"myn"},
            {english:"Erzya",french:"erza",german:"Erza-Mordwinisch",iso2:"myv"},
            {english:"Nahuatl languages",french:"nahuatl, langues",german:"Nahuatl",iso2:"nah"},
            {english:"North American Indian languages",french:"nord-am\u00E9rindiennes, langues",german:"Indianersprachen, Nordamerika (Andere)",iso2:"nai"},
            {english:"Neapolitan",french:"napolitain",german:"Neapel / Mundart",iso2:"nap"},
            {english:"Nauru",french:"nauruan",german:"Nauruanisch",iso2:"nau",iso1:"na"},
            {english:"Navajo",french:"navaho",german:"Navajo-Sprache",iso2:"nav",iso1:"nv"},
            {english:"Ndebele, South",french:"nd\u00E9b\u00E9l\u00E9 du Sud",german:"Ndebele-Sprache (Transvaal)",iso2:"nbl",iso1:"nr"},
            {english:"Ndebele, North",french:"nd\u00E9b\u00E9l\u00E9 du Nord",german:"Ndebele-Sprache (Simbabwe)",iso2:"nde",iso1:"nd"},
            {english:"Ndonga",french:"ndonga",german:"Ndonga",iso2:"ndo",iso1:"ng"},
            {english:"Low German",french:"bas allemand",german:"Niederdeutsch",iso2:"nds"},
            {english:"Nepali",french:"n\u00E9palais",german:"Nepali",iso2:"nep",iso1:"ne"},
            {english:"Nepal Bhasa",french:"nepal bhasa",german:"Newari",iso2:"new"},
            {english:"Nias",french:"nias",german:"Nias-Sprache",iso2:"nia"},
            {english:"Niger-Kordofanian languages",french:"nig\u00E9ro-kordofaniennes, langues",german:"Nigerkordofanische Sprachen (Andere)",iso2:"nic"},
            {english:"Niuean",french:"niu\u00E9",german:"Niue-Sprache",iso2:"niu"},
            {english:"Dutch",french:"n\u00E9erlandais",german:"Niederl\u00E4ndisch",iso2:"nld",iso1:"nl"},
            {english:"Norwegian Nynorsk",french:"norv\u00E9gien nynorsk",german:"Nynorsk",iso2:"nno",iso1:"nn"},
            {english:"Bokm\u00E5l, Norwegian",french:"norv\u00E9gien bokm\u00E5l",german:"Bokm\u00E5l",iso2:"nob",iso1:"nb"},
            {english:"Nogai",french:"noga\u00EF",german:"Nogaisch",iso2:"nog"},
            {english:"Norse, Old",french:"norrois, vieux",german:"Altnorwegisch",iso2:"non"},
            {english:"Norwegian",french:"norv\u00E9gien",german:"Norwegisch",iso2:"nor",iso1:"no"},
            {english:"N\u0027Ko",french:"n\u0027ko",german:"N\u0027Ko",iso2:"nqo"},
            {english:"Pedi",french:"pedi",german:"Pedi-Sprache",iso2:"nso"},
            {english:"Nubian languages",french:"nubiennes, langues",german:"Nubische Sprachen",iso2:"nub"},
            {english:"Classical Newari",french:"newari classique",german:"Alt-Newari",iso2:"nwc"},
            {english:"Chichewa",french:"chichewa",german:"Nyanja-Sprache",iso2:"nya",iso1:"ny"},
            {english:"Nyamwezi",french:"nyamwezi",german:"Nyamwezi-Sprache",iso2:"nym"},
            {english:"Nyankole",french:"nyankol\u00E9",german:"Nkole-Sprache",iso2:"nyn"},
            {english:"Nyoro",french:"nyoro",german:"Nyoro-Sprache",iso2:"nyo"},
            {english:"Nzima",french:"nzema",german:"Nzima-Sprache",iso2:"nzi"},
            {english:"Occitan (post 1500)",french:"occitan (apr\u00E8s 1500)",german:"Okzitanisch",iso2:"oci",iso1:"oc"},
            {english:"Ojibwa",french:"ojibwa",german:"Ojibwa-Sprache",iso2:"oji",iso1:"oj"},
            {english:"Oriya",french:"oriya",german:"Oriya-Sprache",iso2:"ori",iso1:"or"},
            {english:"Oromo",french:"galla",german:"Galla-Sprache",iso2:"orm",iso1:"om"},
            {english:"Osage",french:"osage",german:"Osage-Sprache",iso2:"osa"},
            {english:"Ossetian",french:"oss\u00E8te",german:"Ossetisch",iso2:"oss",iso1:"os"},
            {english:"Turkish, Ottoman (1500-1928)",french:"turc ottoman (1500-1928)",german:"Osmanisch",iso2:"ota"},
            {english:"Otomian languages",french:"otomi, langues",german:"Otomangue-Sprachen",iso2:"oto"},
            {english:"Papuan languages",french:"papoues, langues",german:"Papuasprachen (Andere)",iso2:"paa"},
            {english:"Pangasinan",french:"pangasinan",german:"Pangasinan-Sprache",iso2:"pag"},
            {english:"Pahlavi",french:"pahlavi",german:"Mittelpersisch",iso2:"pal"},
            {english:"Pampanga",french:"pampangan",german:"Pampanggan-Sprache",iso2:"pam"},
            {english:"Panjabi",french:"pendjabi",german:"Pandschabi-Sprache",iso2:"pan",iso1:"pa"},
            {english:"Papiamento",french:"papiamento",german:"Papiamento",iso2:"pap"},
            {english:"Palauan",french:"palau",german:"Palau-Sprache",iso2:"pau"},
            {english:"Persian, Old (ca.600-400 B.C.)",french:"perse, vieux (ca. 600-400 av. J.-C.)",german:"Altpersisch",iso2:"peo"},
            {english:"Persian",french:"persan",german:"Persisch",iso2:"fas",iso1:"fa"},
            {english:"Philippine languages",french:"philippines, langues",german:"Philippinisch-Austronesisch (Andere)",iso2:"phi"},
            {english:"Phoenician",french:"ph\u00E9nicien",german:"Ph\u00F6nikisch",iso2:"phn"},
            {english:"Pali",french:"pali",german:"Pali",iso2:"pli",iso1:"pi"},
            {english:"Polish",french:"polonais",german:"Polnisch",iso2:"pol",iso1:"pl"},
            {english:"Pohnpeian",french:"pohnpei",german:"Ponapeanisch",iso2:"pon"},
            {english:"Portuguese",french:"portugais",german:"Portugiesisch",iso2:"por",iso1:"pt"},
            {english:"Prakrit languages",french:"pr\u00E2krit, langues",german:"Prakrit",iso2:"pra"},
            {english:"Proven\u00E7al, Old (to 1500)",french:"proven\u00E7al ancien (jusqu\u0027\u00E0 1500)",german:"Altokzitanisch",iso2:"pro"},
            {english:"Pushto",french:"pachto",german:"Paschtu",iso2:"pus",iso1:"ps"},
            {english:"Quechua",french:"quechua",german:"Quechua-Sprache",iso2:"que",iso1:"qu"},
            {english:"Rajasthani",french:"rajasthani",german:"Rajasthani",iso2:"raj"},
            {english:"Rapanui",french:"rapanui",german:"Osterinsel-Sprache",iso2:"rap"},
            {english:"Rarotongan",french:"rarotonga",german:"Rarotonganisch",iso2:"rar"},
            {english:"Romance languages",french:"romanes, langues",german:"Romanische Sprachen (Andere)",iso2:"roa"},
            {english:"Romansh",french:"romanche",german:"R\u00E4toromanisch",iso2:"roh",iso1:"rm"},
            {english:"Romany",french:"tsigane",german:"Romani (Sprache)",iso2:"rom"},
            {english:"Romanian",french:"roumain",german:"Rum\u00E4nisch",iso2:"ron",iso1:"ro"},
            {english:"Romanian",french:"roumain",german:"Rum\u00E4nisch",iso2:"ron",iso1:"ro"},
            {english:"Rundi",french:"rundi",german:"Rundi-Sprache",iso2:"run",iso1:"rn"},
            {english:"Aromanian",french:"aroumain",german:"Aromunisch",iso2:"rup"},
            {english:"Russian",french:"russe",german:"Russisch",iso2:"rus",iso1:"ru"},
            {english:"Sandawe",french:"sandawe",german:"Sandawe-Sprache",iso2:"sad"},
            {english:"Sango",french:"sango",german:"Sango-Sprache",iso2:"sag",iso1:"sg"},
            {english:"Yakut",french:"iakoute",german:"Jakutisch",iso2:"sah"},
            {english:"South American Indian languages",french:"sud-am\u00E9rindiennes, langues",german:"Indianersprachen, S\u00FCdamerika (Andere)",iso2:"sai"},
            {english:"Salishan languages",french:"salishennes, langues",german:"Salish-Sprache",iso2:"sal"},
            {english:"Samaritan Aramaic",french:"samaritain",german:"Samaritanisch",iso2:"sam"},
            {english:"Sanskrit",french:"sanskrit",german:"Sanskrit",iso2:"san",iso1:"sa"},
            {english:"Sasak",french:"sasak",german:"Sasak",iso2:"sas"},
            {english:"Santali",french:"santal",german:"Santali",iso2:"sat"},
            {english:"Sicilian",french:"sicilien",german:"Sizilianisch",iso2:"scn"},
            {english:"Scots",french:"\u00E9cossais",german:"Schottisch",iso2:"sco"},
            {english:"Selkup",french:"selkoupe",german:"Selkupisch",iso2:"sel"},
            {english:"Semitic languages",french:"s\u00E9mitiques, langues",german:"Semitische Sprachen (Andere)",iso2:"sem"},
            {english:"Irish, Old (to 900)",french:"irlandais ancien (jusqu\u0027\u00E0 900)",german:"Altirisch",iso2:"sga"},
            {english:"Sign Languages",french:"langues des signes",german:"Zeichensprachen",iso2:"sgn"},
            {english:"Shan",french:"chan",german:"Schan-Sprache",iso2:"shn"},
            {english:"Sidamo",french:"sidamo",german:"Sidamo-Sprache",iso2:"sid"},
            {english:"Sinhala",french:"singhalais",german:"Singhalesisch",iso2:"sin",iso1:"si"},
            {english:"Siouan languages",french:"sioux, langues",german:"Sioux-Sprachen (Andere)",iso2:"sio"},
            {english:"Sino-Tibetan languages",french:"sino-tib\u00E9taines, langues",german:"Sinotibetische Sprachen (Andere)",iso2:"sit"},
            {english:"Slavic languages",french:"slaves, langues",german:"Slawische Sprachen (Andere)",iso2:"sla"},
            {english:"Slovak",french:"slovaque",german:"Slowakisch",iso2:"slk",iso1:"sk"},
            {english:"Slovak",french:"slovaque",german:"Slowakisch",iso2:"slk",iso1:"sk"},
            {english:"Slovenian",french:"slov\u00E8ne",german:"Slowenisch",iso2:"slv",iso1:"sl"},
            {english:"Southern Sami",french:"sami du Sud",german:"S\u00FCdsaamisch",iso2:"sma"},
            {english:"Northern Sami",french:"sami du Nord",german:"Nordsaamisch",iso2:"sme",iso1:"se"},
            {english:"Sami languages",french:"sames, langues",german:"Saamisch",iso2:"smi"},
            {english:"Lule Sami",french:"sami de Lule",german:"Lulesaamisch",iso2:"smj"},
            {english:"Inari Sami",french:"sami d\u0027Inari",german:"Inarisaamisch",iso2:"smn"},
            {english:"Samoan",french:"samoan",german:"Samoanisch",iso2:"smo",iso1:"sm"},
            {english:"Skolt Sami",french:"sami skolt",german:"Skoltsaamisch",iso2:"sms"},
            {english:"Shona",french:"shona",german:"Schona-Sprache",iso2:"sna",iso1:"sn"},
            {english:"Sindhi",french:"sindhi",german:"Sindhi-Sprache",iso2:"snd",iso1:"sd"},
            {english:"Soninke",french:"sonink\u00E9",german:"Soninke-Sprache",iso2:"snk"},
            {english:"Sogdian",french:"sogdien",german:"Sogdisch",iso2:"sog"},
            {english:"Somali",french:"somali",german:"Somali",iso2:"som",iso1:"so"},
            {english:"Songhai languages",french:"songhai, langues",german:"Songhai-Sprache",iso2:"son"},
            {english:"Sotho, Southern",french:"sotho du Sud",german:"S\u00FCd-Sotho-Sprache",iso2:"sot",iso1:"st"},
            {english:"Spanish",french:"espagnol",german:"Spanisch",iso2:"spa",iso1:"es"},
            {english:"Albanian",french:"albanais",german:"Albanisch",iso2:"sqi",iso1:"sq"},
            {english:"Sardinian",french:"sarde",german:"Sardisch",iso2:"srd",iso1:"sc"},
            {english:"Sranan Tongo",french:"sranan tongo",german:"Sranantongo",iso2:"srn"},
            {english:"Serbian",french:"serbe",german:"Serbisch",iso2:"srp",iso1:"sr"},
            {english:"Serer",french:"s\u00E9r\u00E8re",german:"Serer-Sprache",iso2:"srr"},
            {english:"Nilo-Saharan languages",french:"nilo-sahariennes, langues",german:"Nilosaharanische Sprachen (Andere)",iso2:"ssa"},
            {english:"Swati",french:"swati",german:"Swasi-Sprache",iso2:"ssw",iso1:"ss"},
            {english:"Sukuma",french:"sukuma",german:"Sukuma-Sprache",iso2:"suk"},
            {english:"Sundanese",french:"soundanais",german:"Sundanesisch",iso2:"sun",iso1:"su"},
            {english:"Susu",french:"soussou",german:"Susu",iso2:"sus"},
            {english:"Sumerian",french:"sum\u00E9rien",german:"Sumerisch",iso2:"sux"},
            {english:"Swahili",french:"swahili",german:"Swahili",iso2:"swa",iso1:"sw"},
            {english:"Swedish",french:"su\u00E9dois",german:"Schwedisch",iso2:"swe",iso1:"sv"},
            {english:"Classical Syriac",french:"syriaque classique",german:"Syrisch",iso2:"syc"},
            {english:"Syriac",french:"syriaque",german:"Neuostaram\u00E4isch",iso2:"syr"},
            {english:"Tahitian",french:"tahitien",german:"Tahitisch",iso2:"tah",iso1:"ty"},
            {english:"Tai languages",french:"tai, langues",german:"Thaisprachen (Andere)",iso2:"tai"},
            {english:"Tamil",french:"tamoul",german:"Tamil",iso2:"tam",iso1:"ta"},
            {english:"Tatar",french:"tatar",german:"Tatarisch",iso2:"tat",iso1:"tt"},
            {english:"Telugu",french:"t\u00E9lougou",german:"Telugu-Sprache",iso2:"tel",iso1:"te"},
            {english:"Timne",french:"temne",german:"Temne-Sprache",iso2:"tem"},
            {english:"Tereno",french:"tereno",german:"Tereno-Sprache",iso2:"ter"},
            {english:"Tetum",french:"tetum",german:"Tetum-Sprache",iso2:"tet"},
            {english:"Tajik",french:"tadjik",german:"Tadschikisch",iso2:"tgk",iso1:"tg"},
            {english:"Tagalog",french:"tagalog",german:"Tagalog",iso2:"tgl",iso1:"tl"},
            {english:"Thai",french:"tha\u00EF",german:"Thail\u00E4ndisch",iso2:"tha",iso1:"th"},
            {english:"Tibetan",french:"tib\u00E9tain",german:"Tibetisch",iso2:"bod",iso1:"bo"},
            {english:"Tigre",french:"tigr\u00E9",german:"Tigre-Sprache",iso2:"tig"},
            {english:"Tigrinya",french:"tigrigna",german:"Tigrinja-Sprache",iso2:"tir",iso1:"ti"},
            {english:"Tiv",french:"tiv",german:"Tiv-Sprache",iso2:"tiv"},
            {english:"Tokelau",french:"tokelau",german:"Tokelauanisch",iso2:"tkl"},
            {english:"Klingon",french:"klingon",german:"Klingonisch",iso2:"tlh"},
            {english:"Tlingit",french:"tlingit",german:"Tlingit-Sprache",iso2:"tli"},
            {english:"Tamashek",french:"tamacheq",german:"Tama\u009Aeq",iso2:"tmh"},
            {english:"Tonga (Nyasa)",french:"tonga (Nyasa)",german:"Tonga (Bantusprache, Sambia)",iso2:"tog"},
            {english:"Tonga (Tonga Islands)",french:"tongan (\u00CEles Tonga)",german:"Tongaisch",iso2:"ton",iso1:"to"},
            {english:"Tok Pisin",french:"tok pisin",german:"Neumelanesisch",iso2:"tpi"},
            {english:"Tsimshian",french:"tsimshian",german:"Tsimshian-Sprache",iso2:"tsi"},
            {english:"Tswana",french:"tswana",german:"Tswana-Sprache",iso2:"tsn",iso1:"tn"},
            {english:"Tsonga",french:"tsonga",german:"Tsonga-Sprache",iso2:"tso",iso1:"ts"},
            {english:"Turkmen",french:"turkm\u00E8ne",german:"Turkmenisch",iso2:"tuk",iso1:"tk"},
            {english:"Tumbuka",french:"tumbuka",german:"Tumbuka-Sprache",iso2:"tum"},
            {english:"Tupi languages",french:"tupi, langues",german:"Tupi-Sprache",iso2:"tup"},
            {english:"Turkish",french:"turc",german:"T\u00FCrkisch",iso2:"tur",iso1:"tr"},
            {english:"Altaic languages",french:"alta\u00EFques, langues",german:"Altaische Sprachen (Andere)",iso2:"tut"},
            {english:"Tuvalu",french:"tuvalu",german:"Elliceanisch",iso2:"tvl"},
            {english:"Twi",french:"twi",german:"Twi-Sprache",iso2:"twi",iso1:"tw"},
            {english:"Tuvinian",french:"touva",german:"Tuwinisch",iso2:"tyv"},
            {english:"Udmurt",french:"oudmourte",german:"Udmurtisch",iso2:"udm"},
            {english:"Ugaritic",french:"ougaritique",german:"Ugaritisch",iso2:"uga"},
            {english:"Uighur",french:"ou\u00EFgour",german:"Uigurisch",iso2:"uig",iso1:"ug"},
            {english:"Ukrainian",french:"ukrainien",german:"Ukrainisch",iso2:"ukr",iso1:"uk"},
            {english:"Umbundu",french:"umbundu",german:"Mbundu-Sprache",iso2:"umb"},
            {english:"Undetermined",french:"ind\u00E9termin\u00E9e",german:"Nicht zu entscheiden",iso2:"und"},
            {english:"Urdu",french:"ourdou",german:"Urdu",iso2:"urd",iso1:"ur"},
            {english:"Uzbek",french:"ouszbek",german:"Usbekisch",iso2:"uzb",iso1:"uz"},
            {english:"Vai",french:"va\u00EF",german:"Vai-Sprache",iso2:"vai"},
            {english:"Venda",french:"venda",german:"Venda-Sprache",iso2:"ven",iso1:"ve"},
            {english:"Vietnamese",french:"vietnamien",german:"Vietnamesisch",iso2:"vie",iso1:"vi"},
            {english:"Volap\u00FCk",french:"volap\u00FCk",german:"Volap\u00FCk",iso2:"vol",iso1:"vo"},
            {english:"Votic",french:"vote",german:"Wotisch",iso2:"vot"},
            {english:"Wakashan languages",french:"wakashanes, langues",german:"Wakash-Sprachen",iso2:"wak"},
            {english:"Wolaitta",french:"wolaitta",german:"Walamo-Sprache",iso2:"wal"},
            {english:"Waray",french:"waray",german:"Waray",iso2:"war"},
            {english:"Washo",french:"washo",german:"Washo-Sprache",iso2:"was"},
            {english:"Welsh",french:"gallois",german:"Kymrisch",iso2:"cym",iso1:"cy"},
            {english:"Sorbian languages",french:"sorabes, langues",german:"Sorbisch (Andere)",iso2:"wen"},
            {english:"Walloon",french:"wallon",german:"Wallonisch",iso2:"wln",iso1:"wa"},
            {english:"Wolof",french:"wolof",german:"Wolof-Sprache",iso2:"wol",iso1:"wo"},
            {english:"Kalmyk",french:"kalmouk",german:"Kalm\u00FCckisch",iso2:"xal"},
            {english:"Xhosa",french:"xhosa",german:"Xhosa-Sprache",iso2:"xho",iso1:"xh"},
            {english:"Yao",french:"yao",german:"Yao-Sprache (Bantusprache)",iso2:"yao"},
            {english:"Yapese",french:"yapois",german:"Yapesisch",iso2:"yap"},
            {english:"Yiddish",french:"yiddish",german:"Jiddisch",iso2:"yid",iso1:"yi"},
            {english:"Yoruba",french:"yoruba",german:"Yoruba-Sprache",iso2:"yor",iso1:"yo"},
            {english:"Yupik languages",french:"yupik, langues",german:"Ypik-Sprachen",iso2:"ypk"},
            {english:"Zapotec",french:"zapot\u00E8que",german:"Zapotekisch",iso2:"zap"},
            {english:"Blissymbols",french:"symboles Bliss",german:"Bliss-Symbol",iso2:"zbl"},
            {english:"Zenaga",french:"zenaga",german:"Zenaga",iso2:"zen"},
            {english:"Standard Moroccan Tamazight",french:"amazighe standard marocain",german:"Standard-marokkanischen Tamazight",iso2:"zgh"},
            {english:"Zhuang",french:"zhuang",german:"Zhuang",iso2:"zha",iso1:"za"},
            {english:"Chinese",french:"chinois",german:"Chinesisch",iso2:"zho",iso1:"zh"},
            {english:"Zande languages",french:"zand\u00E9, langues",german:"Zande-Sprachen",iso2:"znd"},
            {english:"Zulu",french:"zoulou",german:"Zulu-Sprache",iso2:"zul",iso1:"zu"},
            {english:"Zuni",french:"zuni",german:"Zu\u00F1i-Sprache",iso2:"zun"},
            {english:"No linguistic content",french:"pas de contenu linguistique",german:"Kein linguistischer Inhalt",iso2:"zxx"},
            {english:"Zaza",french:"zaza",german:"Zazaki",iso2:"zza"}
        ];
    }


 }