name: build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '6.x' ]
    steps:
      - name: Checkout FileFlows
        uses: actions/checkout@v3
        with:
          path: FileFlows
      
      - name: Install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
      
      - name: Install dependencies
        run: choco install -y 7zip wixtoolset 
      
      - name: Install ffmpeg
        run: |
          Invoke-WebRequest -Uri 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z' -OutFile 'ffmpeg.7z' 
          7z x ffmpeg.7z
          rm ffmpeg.7z
          mkdir -p c:\utils\ffmpeg\
          mv ffmpeg-*/bin/* c:\utils\ffmpeg\

      - name: Checkout FileFlowsPlugins
        uses: actions/checkout@v3
        with: 
          repository: revenz/FileFlowsPlugins
          path: FileFlowsPlugins

      - name: Build pluigins
        working-directory: ./FileFlows
        run: .\build-plugins.ps1
      
      - name: Build
        working-directory: ./FileFlows/build
        run: .\build.ps1
